Mellanox/network-operator

example/delete-operator.sh, example/delete-rdma-net-ipam.sh, example/delete-rdma-net.sh, example/deploy-operator.sh, example/deploy-rdma-net-ipam.sh, example/deploy-rdma-net.sh, example/deploy/crds/mellanox.com_nicclusterpolicies_crd.yaml, example/deploy/crds/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, example/deploy/operator-ns.yaml, example/deploy/operator.yaml, example/deploy/role.yaml, example/deploy/role_binding.yaml, example/deploy/service_account.yaml, example/network-init/netplan/01-netcfg.yaml, example/network-init/network-scripts/ifcfg-ens2f0, example/networking/multus-daemonset.yml, example/networking/rdma-net-cr-whereabouts-ipam.yml, example/networking/rdma-net-cr.yml, example/networking/whareabouts-daemonset-install.yaml, example/networking/whereabouts.cni.cncf.io_ippools.yaml, example/rdma-gpu-test-pod1.yml, example/rdma-gpu-test-pod2.yml, example/rdma-test-pod1.yml, example/rdma-test-pod2.yml, example/udev/00_persistent_netdev, example/udev/00_persistent_netdev.rules
Add some examples on how to:
1. Persistent netdev name via udev rule
2. Deploy network-operator
3. Depoloy secondary Network: multus + macvlan + whereabouts IPAM
4. Deploy Workloads - RDMA and GPUDirect RDMA
Example should be slightly modified to fit each and every deployment
but provides a good starting point to getting the components deployed.
=> Add Deployment Example

example/deploy/crds/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, example/deploy/operator.yaml, example/rdma-gpu-test-pod1.yml, example/rdma-gpu-test-pod2.yml
This commit modifies example files to deploy the operator
and related components from official mellanox repository.
=> Update container image source to mellanox docker repo

manifests/stage-ofed-driver/0010_ofed-driver-ds.yaml, pkg/nodeinfo/attributes.go, pkg/nodeinfo/attributes_test.go, pkg/state/state_nv_peer.go, pkg/state/state_ofed.go
This PR removed Kernel version dependency from ofed-driver stage
=> Remove kernel ver from mofed driver container

deployment/network-operator/README.md, deployment/network-operator/templates/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, deployment/network-operator/values.yaml
=> Update helm template example for secondary network and MacvlanNetwork

README.md, deploy/crds/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, deployment/network-operator/README.md, deployment/network-operator/templates/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, deployment/network-operator/values.yaml, example/deploy/crds/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
=> Support k8s-rdma-shared-device-plugin device selectors

manifests/stage-ofed-driver/0010_ofed-driver-ds.yaml
=> Fix bad indentation in ofed driver daemonset

deployment/network-operator/README.md, manifests/stage-nv-peer-mem-driver/0010_nv-peer-mem-driver-ds.yaml, pkg/nodeinfo/attributes.go
=> Update NvGPU node selector to nvidia.com/gpu.present

deployment/network-operator/README.md
Add `--devel` flag to allow instalation of v0.X versions
=> Update Deployment README helm install cmd

deployment/network-operator/README.md
=> Update Helm install command

pkg/state/state_nv_peer.go, pkg/state/state_ofed.go, pkg/utils/utils.go
- functin IsCRD is defined but not used
- function GetEnv just a wrapper of the os.Getenv
=> Cleanup pkg/utils/utils.go

deployment/network-operator/README.md
=> Update Readme to default multus image to v3.6.0

README.md, deployment/network-operator/Chart.yaml
update network operator app to v0.3.0
update network operator chart to v0.3.0
update nfd chart to v0.2.0
update Readme nfd to v0.6.0-233-g3e00bfb
=> update charts to v0.3.0

deployment/network-operator/README.md
=> Fix typo in deployment README

.github/ISSUE_TEMPLATE/new-release.md
=> fix minor typos in new release template

README.md, deployment/network-operator/README.md
fix example typo reources => resources
fix broken link for exmple
=> fix typo in README.md

api/v1alpha1/macvlannetwork_types.go, api/v1alpha1/nicclusterpolicy_types.go, config/crd/bases/mellanox.com_macvlannetworks.yaml, config/crd/bases/mellanox.com_nicclusterpolicies.yaml, deployment/network-operator/crds/mellanox.com_macvlannetworks.yaml, deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml
Closes: #136
Partial-Closes: #134
=> Add 'Age' column to CRDs and sync CRDs to helm chart

.travis.yml, Makefile, scripts/check-manifests.sh
CRDs are synced automatically and CI check is added.
Closes: #134
=> Sync CRDs between operator and helm chart

deployment/network-operator/charts/sriov-network-operator/values.yaml, deployment/network-operator/values.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- sriov-network-operator updated to mellanox/sriov-operator:7ad0f8e
- ib-sriov-cni updated to mellanox/ib-sriov-cni:faa9e36
- whereabouts updated to mellanox/whereabouts:v0.3
- sriov-cni updated to nfvpe/sriov-cni:v2.6
=> Update images for v0.4.0

example/sriov-network/sirov-network-node-policy-legacy.yaml, example/sriov-network/sirov-network-node-policy-switchdev.yaml, example/sriov-network/sriov-network.yaml
=> Add examples how to configure and deploy SR-IOV network

deployment/network-operator/Chart.yaml, deployment/network-operator/README.md, scripts/releases/prepare-release.sh, scripts/releases/update-gh-pages.sh
This patch updates chart version and fixes prepare-release.sh
=> Release v0.4.0

README.md, example/README.md
Add info about supported versions of NVIDIA gpu-operator
to README.md and examples.
=> Add notes about compatibility with gpu-operator

example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml
=> Change field name in OCP NicClusterPolicy

deployment/network-operator/values.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
=> Update nv-peer-mem-driver to 1.1-0

deployment/network-operator/Chart.yaml
=> Release v0.5.0

example/sriov-network/sriov-network-node-policy-legacy.yaml, example/sriov-network/sriov-network-pod.yaml, example/sriov-network/sriov-network.yaml
=> Update SR-IOV network examples

deployment/network-operator/README.md, pkg/state/fake_state.go, pkg/state/manager_test.go
=> Add state manager unit tests

deployment/network-operator/Chart.yaml
=> Update Node Feature Discovery chart to 0.8.2

.github/ISSUE_TEMPLATE/new-release.md
Add the step to the release procedure to verify that new image
is successfully pushed to the registry.
=> Update "New release" GitHub issue template

README.md, deployment/network-operator/README.md
Supported NICs are updated too.
=> Update Ubuntu and Helm min version

deployment/network-operator/Chart.yaml, scripts/releases/prepare-release.sh, scripts/releases/update-gh-pages.sh
=> Release v0.6.1

deployment/network-operator/values.yaml
=> Use NGC repository for Network Operator image

deployment/network-operator/Chart.yaml
=> Release v1.1.0-beta.1

example/sriov-network/infiniband/sriov-ib-network.yaml, example/sriov-network/infiniband/sriov-network-node-policy.yaml, example/sriov-network/infiniband/sriov-network-pod.yaml
=> Add examples how to configure SR-IOV Infiniband network

example/dgx-helm-values.yaml
=> Add Helm Chart values example do deploy at NVIDIA DGX SYSTEMS

.gitlab-ci.yml
Added a .gitlab-ci.yml file to run regression on QA INFRA. The CI
would build the latest image, push it to harbor, and trigger QA regression.
Signed-off-by: abdallahyas <abdallahyas@mellanox.com>
=> Add gitlab CI yaml file

README.md
=> fix trivial typo

deployment/network-operator/Chart.yaml
=> Release v1.1.0-beta.5

README.md, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, example/rdma-gpu-test-pod1.yml, example/rdma-gpu-test-pod2.yml, example/rdma-test-pod1.yml, example/rdma-test-pod2.yml
=> Align Shared Device Plugin examples with default configuration

deployment/network-operator/README.md, deployment/network-operator/values.yaml
Signed-off-by: Alexander Maslennikov <amaslennikov@nvidia.com>
=> Update SR-IOV Network Operator dependencies

deployment/network-operator/Chart.yaml
Signed-off-by: Alexander Maslennikov <amaslennikov@nvidia.com>
=> Release v1.1.0-rc.1

.github/ISSUE_TEMPLATE/new-release.md, scripts/releases/update-gh-pages.sh
Rearranging some steps and adding more details
Signed-off-by: Alexander Maslennikov <amaslennikov@nvidia.com>
=> Update new release template

example/crs/mellanox.com_v1alpha1_hostdevicenetwork_cr-ocp.yaml, example/crs/mellanox.com_v1alpha1_macvlannetwork_cr-ocp.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml
=> Update CRDs examples for OCP

deployment/network-operator/Chart.yaml
=> Release v1.1.0-rc.2

bundle/1.1.0/manifests/k8s.cni.cncf.io_network-attachment-definitions.yaml, bundle/1.1.0/manifests/mellanox.com_hostdevicenetworks.yaml, bundle/1.1.0/manifests/mellanox.com_macvlannetworks.yaml, bundle/1.1.0/manifests/mellanox.com_nicclusterpolicies.yaml, bundle/1.1.0/manifests/network-operator.clusterserviceversion.yaml, bundle/1.1.0/manifests/nvidia-network-operator-controller-manager-metrics-service_v1_service.yaml, bundle/1.1.0/manifests/nvidia-network-operator-manager-config_v1_configmap.yaml, bundle/1.1.0/manifests/nvidia-network-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/1.1.0/metadata/annotations.yaml, bundle/1.1.0/tests/scorecard/config.yaml, bundle/manifests/k8s.cni.cncf.io_network-attachment-definitions.yaml, bundle/manifests/mellanox.com_hostdevicenetworks.yaml, bundle/manifests/mellanox.com_macvlannetworks.yaml, bundle/manifests/mellanox.com_nicclusterpolicies.yaml, bundle/manifests/network-operator.clusterserviceversion.yaml, bundle/manifests/nvidia-network-operator-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/nvidia-network-operator-manager-config_v1_configmap.yaml, bundle/manifests/nvidia-network-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml
=> Add Network Operator v1.1.0 bundle for OCP 4.9

deployment/network-operator/values.yaml
=> Update SR-IOV Network Operator to v1.1.0

deployment/network-operator/values.yaml
=> Update SR-IOV operator to support BlueField2 NICs

deployment/network-operator/Chart.yaml
=> Release Network Operator v1.2.0-beta.1

README.md, deployment/network-operator/README.md
=> Mark ConnectX-6 Lx as not supported

bundle/manifests/nvidia-network-operator.clusterserviceversion.yaml, config/manifests/bases/nvidia-network-operator.clusterserviceversion.yaml
- Add RelatedImages field
- Add Replaces field
- Add NFD labels information in general description
=> Improvements in CSV bundle

bundle/manifests/nvidia-network-operator.clusterserviceversion.yaml, config/samples/mellanox.com_v1alpha1_hostdevicenetwork.yaml, config/samples/mellanox.com_v1alpha1_macvlannetwork.yaml, config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml
=> Add alm-examples to OLM bundle

deployment/network-operator/Chart.yaml
=> Release Network Operator v1.2.0-beta.2

deployment/network-operator/Chart.yaml
=> Release Network Operator v1.2.0-beta.3

deployment/network-operator/values.yaml
=> Bump whereabouts version to v0.5.2

deployment/network-operator/README.md, deployment/network-operator/values.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
=> Update RDMA Shared Device Plugin to v1.3.2

deployment/network-operator/Chart.yaml
=> Release Network Operator v1.2.0-rc.1

.gitignore, pkg/state/state_hostdevice_network.go, pkg/state/state_macvlan_network.go
=> Fix call to errors.Wrap with nil error

ci/image-push.Jenkinsfile
Added a Jenkinsfile to build and push the projects images to NVIDIA
internal container registry.
=> Add image push CD for pushing images ubon code merge and tag creation

deployment/network-operator/Chart.yaml, deployment/network-operator/templates/_helpers.tpl, deployment/network-operator/values.yaml
=> Release Network Operator v1.3.0-beta.1

deployment/network-operator/values.yaml
=> Bump SR-IOV Network Operator to v1.2.0

deployment/network-operator/Chart.yaml
=> Release Network Operator v1.3.0-beta.2

pkg/upgrade/upgrade_state.go, pkg/upgrade/upgrade_state_test.go
=> Fix a check of OFED pod termination

deployment/network-operator/Chart.yaml
=> Release Network Operator v1.3.0-beta.4

deployment/network-operator/Chart.yaml, deployment/network-operator/README.md, deployment/network-operator/values.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, example/dgx-helm-values.yaml
=> Release Network Operator v1.3.0

bundle/manifests/mellanox.com_ipoibnetworks.yaml, bundle/manifests/mellanox.com_nicclusterpolicies.yaml, bundle/manifests/nvidia-network-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml
=> Update OCP bundle for Network Operator v1.3.0 release

docs/operator-bundle.md
=> Enhance bundle documentation

.golangci.yml, Makefile, api/v1alpha1/groupversion_info.go, config/crd/bases/mellanox.com_hostdevicenetworks.yaml, config/crd/bases/mellanox.com_ipoibnetworks.yaml, config/crd/bases/mellanox.com_macvlannetworks.yaml, config/crd/bases/mellanox.com_nicclusterpolicies.yaml, config/rbac/role.yaml, controllers/hostdevicenetwork_controller.go, controllers/ipoibnetwork_controller.go, controllers/macvlannetwork_controller.go, controllers/nicclusterpolicy_controller.go, controllers/upgrade_controller.go, deployment/network-operator/crds/mellanox.com_hostdevicenetworks.yaml, deployment/network-operator/crds/mellanox.com_ipoibnetworks.yaml, deployment/network-operator/crds/mellanox.com_macvlannetworks.yaml, deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml, pkg/state/fake_manager.go, pkg/state/state_cni_plugins.go, pkg/state/state_ipoib_cni.go, pkg/state/state_ipoib_network.go, pkg/state/state_macvlan_network.go, pkg/state/state_multus_cni.go, pkg/state/state_nv_peer.go, pkg/state/state_ofed.go, pkg/state/state_pod_security_policy.go, pkg/state/state_shared_dp.go, pkg/state/state_sriov_dp.go, pkg/state/state_whereabouts_cni.go
Update controller-gen to 0.10.0
Update golangci-lint to 1.49.0
Drop deprecated linters
Reformat files
=> Update build-time dependencies to work with go1.19

pkg/upgrade/drain_manager.go
Signed-off-by: Shiva Krishna, Merla <smerla@nvidia.com>
=> Drain timeout is set in nanoseconds while input is in seconds

controllers/upgrade_controller.go
=> Do not return error if NicCluserPolicy is not deployed

deployment/network-operator/Chart.yaml
=> Release Network Operator v1.4.0-beta.2

example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
=> Add NicClusterPolicy example with IPoIB CNI

deployment/network-operator/Chart.yaml
=> Release Network Operator v1.4.0-rc.1

bundle/manifests/mellanox.com_hostdevicenetworks.yaml, bundle/manifests/mellanox.com_ipoibnetworks.yaml, bundle/manifests/mellanox.com_macvlannetworks.yaml, bundle/manifests/mellanox.com_nicclusterpolicies.yaml, bundle/manifests/nvidia-network-operator-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/nvidia-network-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml
=> Update OCP bundle for v1.4.0

deployment/network-operator/Chart.yaml
=> Release Network Operator v23.1.0-beta.1

deployment/network-operator/Chart.yaml
=> Release Network Operator v23.1.0-beta.2

deployment/network-operator/Chart.yaml
=> Release Network Operator v23.1.0-beta.3

Makefile, scripts/releases/prepare-release.sh
=> Add Makefile target to build helm chart

controllers/nicclusterpolicy_controller.go
When MOFED driver is not configured, use Patch
instead of Update as done when updating node labels when MOFED driver is specified.
In addition, enhance errors in case of failure.
=> Use Patch to update node label

go.mod, go.sum
=> Replace go-restful lib

deployment/network-operator/README.md, deployment/network-operator/values.yaml
=> Update nv-ipam version

api/v1alpha1/nicclusterpolicy_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/mellanox.com_nicclusterpolicies.yaml, deployment/network-operator/README.md, deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml, deployment/network-operator/templates/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, deployment/network-operator/values.yaml, manifests/stage-container-networking-plugins/0010-container-networking-plugins-ds.yml, manifests/stage-ib-kubernetes/0070-deployment.yaml, manifests/stage-ipoib-cni/0050-ipoib-cni-ds.yml, manifests/stage-multus-cni/0050-multus-ds.yml, manifests/stage-nv-peer-mem-driver/0050_nv-peer-mem-driver-ds.yaml, manifests/stage-ofed-driver/0050_ofed-driver-ds.yaml, manifests/stage-rdma-device-plugin/0060_rdma-shared-dev-plugin-ds.yaml, manifests/stage-sriov-device-plugin/0030-sriov-dp-daemonset.yml, manifests/stage-whereabouts-cni/0050-whereabouts-ds.yaml, pkg/state/state_cni_plugins.go, pkg/state/state_ib_kubernetes.go, pkg/state/state_ipoib_cni.go, pkg/state/state_multus_cni.go, pkg/state/state_nv_peer.go, pkg/state/state_ofed.go, pkg/state/state_shared_dp.go, pkg/state/state_sriov_dp.go, pkg/state/state_whereabouts_cni.go
- remove master and control-plane tolerations from
all DaemonSets
- remove anti affinity rules from DaemonSets
- add support to configure custom tolerations for components
=> Align nodeAffinity rules and default taints for managed components, add support for custom tolerations

.github/workflows/build.yml, Makefile
=> Add CI check for generated files

config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml, deployment/network-operator/values.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, hack/release.yaml
(cherry picked from commit 2ad11b4db4333c5f24734f9549d3dd083b2a5d72)
=> Update MOFED image to 23.04-0.5.3.3.1

controllers/predicate.go
Predicate now will ignore following fields for Deployment obj:
- metadata.generation
- status.observedGeneration
- metadata.annotations["deployment.kubernetes.io/revision"]
fixes #548
=> Improve IgnoreSameContentPredicate to handle Deployment obj correctly

README.md, example/crs/mellanox.com_v1alpha1_macvlannetwork_cr-nvidia-ipam.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml, hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.template
Add basic examples for NVIDIA IPAM configuration
=> Add examples for NVIDIA IPAM to README.md

README.md, deployment/network-operator/README.md, deployment/network-operator/values.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml, hack/release.yaml, manifests/state-nv-ipam-cni/020-cluster-role.yaml, manifests/state-nv-ipam-cni/040-nv-ipam-controller.yaml
+ update nvidia-ipam to v0.0.3 (supports HA mode)
=> Update manifests to deploy nvidia-ipam in HA mode

example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml, hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.template
current example doesnt really work for more than
two nodes
=> update nvidia-ipam cr example

README.md, docs/mofed-container-env-vars.md
Add README for MOFED container environment variables
=> Document MOFED container env vars

config/manager/kustomization.yaml, config/rbac/role.yaml, controllers/hostdevicenetwork_controller.go, controllers/ipoibnetwork_controller.go, controllers/macvlannetwork_controller.go, controllers/nicclusterpolicy_controller.go, controllers/upgrade_controller.go
Revert: Tighten up controller roles #596
=> Revert: Tighten up controller roles

.github/workflows/commit-msg-chk.yaml, CONTRIBUTING.md
=> ci: add conventional commit check for PRs

deployment/network-operator/templates/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, manifests/state-sriov-device-plugin/0030-sriov-dp-daemonset.yml
This patch fixes errors introduced in #627.
=> fix: device plugins CDI mode manifests

pkg/state/factory.go
a recent refactor missed this comment.
=> refactor: fix typo in comment

config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml, deployment/network-operator/values.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, hack/release.yaml
Update MOFED image to the latest version
=> chore: Update MOFED to v23.10-0.3.8.0

config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml, deployment/network-operator/values.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, hack/release.yaml
Bump MOFED version to 23.10-0.4.1.0
=> chore: Bump MOFED version to 23.10-0.4.1.0

bundle/metadata/annotations.yaml, config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml, deployment/network-operator/values.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, hack/release.yaml
Update MOFED and OCP version  for RC1
=> chore: Update MOFED and OCP version

controllers/nicclusterpolicy_controller.go
Fix behaviour of OFED wait label when
there is no OFED spec in the NicClusterPolicy.
=> fix: OFED wait label behaviour

deployment/network-operator/values.yaml, hack/release.yaml
Update SR-IOV Network Operator image
=> chore: Update SR-IOV Network Operator image

pkg/migrate/migrate_test.go, pkg/migrate/suite_test.go
Test clearing of State label on NV IPAM config map
=> chore: Add Migrate test

deployment/network-operator/Chart.yaml, deployment/network-operator/values.yaml, hack/release.yaml
Release Network Operator 23.10.0-rc.4
=> chore: Release Network Operator 23.10.0-rc.4

README.md
update official doc link  in the README.md
=> chore: update official doc link

api/v1alpha1/validator/hostdevicenetwork_webhook.go, api/v1alpha1/validator/nicclusterpolicy_webhook.go, go.mod, go.sum
Fix an issue where webhooks were carrying a global state which could lead to concurrency bugs.
Fixes #714
=> fix: Race condition in webhooks

api/v1alpha1/nicclusterpolicy_types.go, api/v1alpha1/validator/nicclusterpolicy_webhook.go, api/v1alpha1/validator/nicclusterpolicy_webhook_test.go, pkg/state/container_resources.go, pkg/state/dummy_provider.go, pkg/state/factory.go, pkg/state/manifest_renderer.go, pkg/state/state_cni_plugins.go, pkg/state/state_ib_kubernetes.go, pkg/state/state_ib_kubernetes_test.go, pkg/state/state_ipoib_cni.go, pkg/state/state_ipoib_cni_test.go, pkg/state/state_multus_cni.go, pkg/state/state_nic_feature_discovery.go, pkg/state/state_nv_ipam_cni.go, pkg/state/state_ofed.go, pkg/state/state_ofed_test.go, pkg/state/state_shared_dp.go, pkg/state/state_skel.go, pkg/state/state_sriov_dp.go, pkg/state/state_sriov_dp_test.go, pkg/state/state_whereabouts_cni.go
Add webhook validation for:
- Container names used in resource requirements
- Resource requests should not exceed limits
- Requirements should not be zero
- Requirements should not be empty if declared
=> feat: Validate container resources in the webhook

deployment/network-operator/templates/operator.yaml, deployment/network-operator/values.yaml, hack/templates/values/values.template
Add support to configure operator resources in
the Helm templating.
Fixes #722
=> bug: Support operator resources in helm

deployment/network-operator/README.md
Update Helm README with `useCDI`
=> chore: Update Helm README with useCDI

docs/automatic-ofed-upgrade.md
- Fix the title to contain the right state name
- Add a note about safeLoad annotation
=> fix: add extra detail to Troubleshooting section of ofed-upgrade doc

config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml, deployment/network-operator/values.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, hack/release.yaml
change default driver container to doca-driver
this container provides same functionality but
is part of the doca host software suite
=> feat: change to doca driver

Dockerfile, pkg/state/state_ofed.go
Add support for multi arch images build
=> feat: Add support for multi arch images build

Makefile
Update the tool install flow in the Makefile to ensure that all tools are now installed with a version suffix. This means that tools will now be pinned to the versions set for them in their Makefile.
Fixes https://github.com/Mellanox/network-operator/issues/444
=> chore: Update tool install in Makefile

deployment/network-operator/templates/NOTES.txt
clarify deprecation note in helm
=> chore: clarify deprecation note in helm

controllers/macvlannetwork_controller_test.go, controllers/suite_test.go
Add env-test for macvlan network controller.
=> chore: add test to macvlan controller

config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml, deployment/network-operator/values.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, hack/release.yaml
Update MOFED to v24.01-0.3.3.1
=> chore: Update MOFED to v24.01-0.3.3.1

deployment/network-operator/values.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml, hack/release.yaml
(cherry picked from commit e99ba01ae464ff5c9a8384e7e59caecb5e918dc3)
=> chore: Bump IPoIB CNI image to the latest

Dockerfile, Makefile, README.md, skaffold.yaml
Signed-off-by: killianmuldoon <cilliancapi@gmail.com>
(cherry picked from commit 08d0048873584e51b6b092fa83bb73e9bf255256)
=>  feat: Multi-arch image building

pkg/state/state_macvlan_network_test.go
=> chore: add state macvlan test

manifests/state-nic-feature-discovery/030-nic-feature-discovery-ds.yaml, manifests/state-nv-ipam-cni/040-nv-ipam-node.yaml
Signed-off-by: Jessica Xie <jessicaxie@cohere.com>
(cherry picked from commit fd7a346d86f21752d559373846ec823d975a5c4d)
=> fix: Toleration indentation problem

.gitignore, Makefile, docs/local-development.md, skaffold.yaml
Fix a couple of minor issues related to the skaffold build.
Context: https://github.com/Mellanox/network-operator/pull/768#discussion_r1497149678
=> chore: fix skaffold build issues

README.md
=> chore: update official doc version

bundle/manifests/nvidia-network-operator.clusterserviceversion.yaml, config/manifests/bases/nvidia-network-operator.clusterserviceversion.yaml, deployment/network-operator/README.md
=> fix: Update documentation links

pkg/state/state_ipoib_network_test.go, pkg/state/state_test_common.go
Add tests to ipoib network state
=> chore: add tests to ipoib network state

pkg/utils/utils_suite_test.go, pkg/utils/utils_test.go
Add test suite for utils package.
=> chore: utils test suite

api/v1alpha1/validator/nicclusterpolicy_webhook.go, go.mod
=> chore: use stdlib slices

manifests/state-ofed-driver/0050_ofed-driver-ds.yaml, pkg/state/state_ofed.go, pkg/state/state_ofed_test.go
- Add additional mounts to DTK container
- Fix additional mounts handling issue introduced in #707
=> fix: DTK additional mounts

README.md, deployment/network-operator/values.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml, hack/release.yaml
This version contains bug fixes and other improvements.
Change log for the version: https://github.com/Mellanox/nvidia-k8s-ipam/releases/tag/v0.1.2
=> fix: update nv-ipam to v0.1.2

deployment/network-operator/values.yaml, hack/templates/values/values.template
Temporary workaround for CI issue
=> fix: disable deployment of the ovs-cni by default

deployment/network-operator/values.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml, hack/release.yaml
Upgrade to a new non-release version
=> chore: upgrade sriov-network-device-plugin version

docs/automatic-ofed-upgrade.md
=> chore: fix typo in doc

deployment/network-operator/charts/sriov-network-operator/README.md, deployment/network-operator/charts/sriov-network-operator/templates/clusterrole.yaml, deployment/network-operator/charts/sriov-network-operator/templates/operator.yaml, deployment/network-operator/charts/sriov-network-operator/values.yaml
Update SR-IOV Network Operator chart to deploy RDMA CNI
=> chore: Update SR-IOV Network Operator chart to deploy RDMA CNI

deployment/network-operator/values.yaml, hack/release.yaml
Update ovs-cni to latest downstream version
=> chore: update ovs-cni image

deployment/network-operator/values.yaml, hack/release.go, hack/release.yaml, hack/templates/values/values.template
Allow to configure and deploy RDMA CNI image
=> feat: Allow to configure and deploy RDMA CNI image

config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml, deployment/network-operator/values.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, hack/release.yaml
Update DOCA Driver image to 24.04-0.6.5.2-0
=> chore: Update DOCA Driver image to 24.04-0.6.5.2-0

deployment/network-operator/charts/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovnetworkpoolconfigs.yaml
Sync SR-IOV Network Operator CRDs
=> fix: Sync SR-IOV Network Operator CRDs

pkg/state/state_ofed.go
Signed-off-by: killianmuldoon <kmuldoon@nvidia.com>
(cherry picked from commit 6733ce696a471fd0b22dd4f3a1973e924aa76c8b)
=> feat: Add RHEL support in ofed config

hack/release.go, hack/scripts/ocp-bundle-postprocess.sh
Make sure that `release.go` exit with error code on failure.
=> chore: fail on error on make bundle

go.mod, go.sum
=> chore: udpate go-containerregistry

hack/templates/values/values.template
Related to #1052
Signed-of-by: Fred Rolland <frolland@nvidia.com>
=> bug: fix helm values generation

.github/workflows/docs-ci-trigger.yaml
bugfix triggering from upstream workflow.
=> fix: downstream workflow trigger token and non-dynamic reference

api/v1alpha1/validator/nicclusterpolicy_webhook_test.go, webhook-schemas/rdma_shared_device_plugin.json, webhook-schemas/sriov_network_device_plugin.json
bug: fixing nicclusterpolicy validation for 'RdmaSharedDevicePluginConfig.config, SriovDevicePlugin.resourceList' empty list
=> bug: fixing nicclusterpolicy validation for empty config list

api/v1alpha1/nicclusterpolicy_types.go, config/crd/bases/mellanox.com_nicclusterpolicies.yaml, deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml
```
$ kubectl get ncp
NAME                 STATUS     AGE
nic-cluster-policy   notReady   2024-09-01T10:25:24Z
```
=> chore: add short name for NCP

pkg/state/state_ofed.go, pkg/state/state_ofed_test.go
Add required mounts for MOFED in case of SLES.
=> feat: Add SLES subscription mounts

deployment/network-operator/values.yaml, hack/release.yaml
This if follow-up for #1213 to remote trailing slash.
=> fix: Update Network Operator image registry

deployment/network-operator/values.yaml, hack/release.yaml
Align SRIOV NO images to use nvstaging
=> chore: use nvstaging for master

deployment/network-operator/Chart.yaml, hack/release.yaml
This is a manual PR until #1203 is merged.
=> task: Release Network Operator 25.1.0-beta.2

deployment/network-operator/values.yaml, hack/release.yaml
Align NIC FW operator version with DS and Helm
=> bug: nic fw operator version

.github/workflows/ci.yaml
Changes:
- Added Docker tag with `$git_sha`.
- Added chart packages & push with `$current_version-$git_sha` (like for default branch pushes) **also on git tag push events**.
- Refactored step logic, to accommodate above change as briefly as possible.
- Shifted job conditioning to job level instead of repeating it in each step (more correct scope).
=> task: push git_sha docker tag and upload consistent chart version also on git tag (for verification team)

.github/workflows/ci.yaml
See:
https://github.com/redhat-openshift-ecosystem/certified-operators/pull/4817/files#diff-0d61a7ad42a2b098687282762faf8b176a0069fb961afb2eb111419912895030R5
https://github.com/redhat-openshift-ecosystem/certified-operators/pull/4817/files#diff-0d61a7ad42a2b098687282762faf8b176a0069fb961afb2eb111419912895030R459
=> bug: NO image registry on GA for bundle

.github/workflows/ci.yaml
In case of building with commit hash, use nvstaging
=> bug: ocp bundle registry fix

Makefile, bundle/manifests/nvidia-network-operator.clusterserviceversion.yaml, config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml, hack/release.go, hack/templates/samples/mellanox.com_v1alpha1_nicclusterpolicy.template
Except for DOCA driver for now
=> bug: use SHA256 in alm-example

example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-full.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml, hack/release.yaml
changelog: https://github.com/Mellanox/ipoib-cni/releases/tag/v1.2.1 CVE fixes and go version upgrade
=> chore: upgrade ipoib-cni to v1.2.1

api/v1alpha1/nicclusterpolicy_types.go, config/crd/bases/mellanox.com_nicclusterpolicies.yaml, deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml, deployment/network-operator/values.yaml, hack/templates/values/values.template
=> bug: replace MOFED to DOCA on API docs

deployment/network-operator/charts/node-feature-discovery/templates/post-delete-job.yaml, deployment/network-operator/charts/node-feature-discovery/values.yaml, deployment/network-operator/values.yaml, hack/templates/values/values.template
chore: add cleanupLabels
Signed-off-by: Aleksey Senin <alekseys@nvidia.com>
=> bug: Cleanup labels

.github/workflows/checks.yaml, .github/workflows/ci.yaml, .github/workflows/codeql.yml, .github/workflows/commit-msg-chk.yaml, .github/workflows/docs-ci-trigger.yaml, .github/workflows/release-pr-checker.yaml, .github/workflows/release.yaml
=> chore: align runners

deployment/network-operator/templates/role.yaml
add sriovnetworkpoolconfigs to role in Helm template.
=> fix: spectrumx operator role

deployment/network-operator/templates/operator.yaml, deployment/network-operator/values.yaml, go.mod, go.sum, hack/templates/values/values.template
=> chore: Adding nodeMaintenance prefix name in upgrade requestor mode

example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-full-ocp.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-full.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, hack/release.yaml
=> chore: update DOCA OFED to 25.04-0.6.1.0-2

.github/workflows/ci.yaml
Make sure the values.yaml point to the right repositories
=> fix: ci update repository for GA

.github/workflows/release.yaml
A small improvement for traceability.
=> feat: PR body will now contain link to specific workflow run that created it

api/v1alpha1/nicclusterpolicy_types.go, config/crd/bases/mellanox.com_nicclusterpolicies.yaml, deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml, deployment/network-operator/values.yaml, hack/templates/values/values.template
Updating files that affect documentation (CRD and Helm values)
=> fix: update naming to DOCA-OFED Driver

deployment/network-operator/values.yaml, hack/release.go, hack/release.yaml, hack/templates/values/values.template
This adds NFD to the release components and updates its Helm values
=> chore: add node-feature-discovery to release.yaml and update Helm values

deployment/network-operator/charts/maintenance-operator-chart/templates/deployment.yaml
Updating maintenance OP sub-chart changes
Mellanox/maintenance-operator#108
=> fix: revert maintenance OP sub-chart 'imagePullSecrets' 

example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-full-ocp.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-full.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml, example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml, hack/release.yaml
=> ci: update OFED version to doca3.1.0-25.07-0.9.6.0-0

api/v1alpha1/validator/nicclusterpolicy_webhook.go, api/v1alpha1/validator/nicclusterpolicy_webhook_test.go, pkg/state/state_ofed.go, pkg/state/state_ofed_test.go
If OFED version is in SHA256, it will be used as is.
=> feat: Support sha256 for ofed version
