Mellanox/network-operator

- pkg/state/state_ofed.go
The original name was too generic
> Rename internal struct runtimeSpec -> ofedRuntimeSpec

- pkg/config/config.go
- pkg/controller/nicclusterpolicy/nicclusterpolicy_controller.go
Specifying uint is in my opinion clearer than time.Duration
which requires the user to suffix the input with a time marker e.g '5s'
In addition we do not want to allow other time granularity like minutes
at this point.
> Modify RequeueTimeSeconds to be uint

- deploy/operator.yaml
- deploy/role.yaml
Added the missing STATE_MANIFEST_BASE_DIR environment variable
in the deploy/operator.yaml file. Also added the name field for
the cluster role definition inside deploy/role.yaml file.
> Added missing STATE_MANIFEST_BASE_DIR in the operator pod.

- deploy/crds/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- manifests/stage-nv-peer-mem-driver/0010_nv-peer-mem-driver-ds.yaml
- pkg/nodeinfo/attributes.go
- pkg/state/factory.go
- pkg/state/state_nv_peer.go
This commit adds a new state that deploys
NV Peer memory driver container on nodes that have
both mellanox and nvidia hardware.
- Add manifest file
- Nv peer memory state implementation
- Instantiate new state in factory
- Extend node attributes with nvidia gpu pci label
> State NV peer mem driver

- manifests/stage-nv-peer-mem-driver/0010_nv-peer-mem-driver-ds.yaml
- manifests/stage-ofed-driver/0010_ofed-driver-ds.yaml
This would ensure proper operation of the operator
in regards to dependencies between components as
the network-operator waits for one stage group to be done
before moving the the other.
In addition, liveliness probes would trigger a restart
of the container in case the driver was suddenly unloaded
for some reason.
> Add Probes to driver container daemonsets

- example/deploy/operator.yaml
This commit updates example deployment to deploy a v0.1.0
tagged operator image as a prestep to tagging the repository.
> Update deployment example with v0.1.0 tagged operator image

- deploy/crds/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- deploy/operator-resources-ns.yaml
- deploy/operator.yaml
- deploy/role.yaml
- deploy/role_binding.yaml
- example/deploy-operator.sh
- example/deploy/crds/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- example/deploy/operator-resources-ns.yaml
- example/deploy/operator.yaml
- example/deploy/role.yaml
- example/deploy/role_binding.yaml
- pkg/consts/consts.go
- pkg/state/state_nv_peer.go
- pkg/state/state_ofed.go
- pkg/state/state_shared_dp.go
Separate deployed network operator namespaced resources  from the namespace the operator is deployed in.
This PR modifies network operator to deploy namespaced resources to a predefined namespace, `mlnx-network-operator-resources`.
This will allow consolidation of resources regardless of the namespace the operator is deployed in.
> Separate network operator resources

- deploy/crds/mellanox.com_nicclusterpolicies_crd.yaml
- deploy/crds/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- deploy/operator.yaml
- deploy/role.yaml
- deploy/role_binding.yaml
- example/deploy/crds/mellanox.com_nicclusterpolicies_crd.yaml
- example/deploy/crds/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- example/deploy/operator.yaml
- example/deploy/role.yaml
- example/deploy/role_binding.yaml
- pkg/apis/mellanox/v1alpha1/nicclusterpolicy_types.go
Change nicclusterpolicy CRD to be cluster scoped
This commit modifies nicclusterpolicy CRD to be cluster
scope instead of namespace scope as the CRD defines
cluster wide parameters that are not confined to a certain
namespace.
- Update CRD to be Cluster scoped
- Update deploy templates
- Update example deployment templates
> nicclusterpolicy as Cluster resource

- pkg/consts/consts.go
This commit aligns the defiend log levels with
the default logging implementation used (zap).
Leveled log messages will now be printed with
their proper string and adhere to the log level
provided to the process via --zap-level flag.
> Align log levels with operator-sdk default impl

- manifests/stage-nv-peer-mem-driver/0010_nv-peer-mem-driver-ds.yaml
- manifests/stage-ofed-driver/0010_ofed-driver-ds.yaml
- manifests/stage-rdma-device-plugin/0020-k8s-rdma-shared-dev-plugin-ds.yaml
This commit aligns tolerations for daemonsets
and removes the "tolerate all" entry which should
not have been there in the first place.
> Align Tolerations for daemonsets

- example/delete-rdma-net-hostdev-ipam.sh
- example/delete-rdma-net-hostdev.sh
- example/deploy-rdma-net-hostdev-ipam.sh
- example/deploy-rdma-net-hostdev.sh
- example/networking/rdma-net-hostdev-cr-whereabouts-ipam.yml
- example/networking/rdma-net-hostdev-cr.yml
This commit adds Example on how to deploy a secondary
RDMA network using host-device CNI.
This is intended to be used to directly assign the physical
NIC interface to the pod when DPDK application need to run
but SR-IOV is not utilized.
> Add host-device secondary network example deployment

- README.md
- deploy/crds/mellanox.com_nicclusterpolicies_crd.yaml
- deploy/crds/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- deployment/network-operator/crds/mellanox.com_nicclusterpolicies_crd.yaml
- deployment/network-operator/templates/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- example/deploy/crds/mellanox.com_nicclusterpolicies_crd.yaml
- example/deploy/crds/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- go.mod
- pkg/apis/mellanox/v1alpha1/nicclusterpolicy_types.go
- pkg/consts/consts.go
- pkg/controller/nicclusterpolicy/nicclusterpolicy_controller.go
Network Operator watches only for NicPolicy with name "nic-cluster-policy" to prevent polices overlapping
Signed-off-by: Mamduh Alassi <mamduhala@mellanox.com>
Fixes #17
> Network Operator watches for NicClusterPolicy with predefined name

- pkg/state/manager.go
state manager should not emit error log
when state group is not ready. this is not an error
modify to INFO log
> Minor log level fix

- deploy/operator.yaml
- deployment/network-operator/templates/operator.yaml
- deployment/network-operator/values.yaml
- example/deploy/operator.yaml
This Commit modifies operator deployment yamls
to deploy operator on master node.
- Add nodeSelector to deploy on master node and matching
toleration.
- Support specifying nodeSelector in addition to toleration
in helm deployment which by default will deploy the operator
on master node.
> Deploy network operator controller on master

- deployment/network-operator/charts/node-feature-discovery/templates/worker.yaml
hostNetwork is not needed for NFD since v0.6.0
fixes #39
> Remove hostNetwork from Node feature Discovery helm deployment chart

- manifests/stage-ofed-driver/0010_ofed-driver-ds.yaml
When deploying the ofed-driver on a non-supported kernel, the
container will try to rebuild the KDMS to support the new kernel,
this process has varying times based on the server capabilities.
This patch increases the timeout of ofed-driver startupProbe to 10
minutes as a precaution for somewhat old servers to not restart
container build waiting for the modules to be rebuilt.
Signed-off-by: abdallahyas <abdallahyas@mellanox.com>
> Increase ofed-driver startupProbe timeout to 10 minutes

- manifests/stage-nv-peer-mem-driver/0010_nv-peer-mem-driver-ds.yaml
- manifests/stage-ofed-driver/0010_ofed-driver-ds.yaml
- pkg/nodeinfo/attributes.go
- pkg/nodeinfo/attributes_test.go
- pkg/state/state_nv_peer.go
- pkg/state/state_ofed.go
OSNameFull can be derrived from OSName and OSVer
Remove OSNameFull from Node Attributes package.
Fixes #42
> Cleanup nodeinfo.AttrTypeOSNameFull

- pkg/state/state_skel.go
ResourceVersion is required to update CRD instances
Fixes #47
> Add resource version for object when using CreateAndUpdateObjs

- deployment/network-operator/templates/operator.yaml
- deployment/network-operator/values.yaml
This commit removes the default node selector
to schedule the operator on the master node.
instead a preffered node affinity is introduced
allowing the human operator(or otherwise) to deploy
it on other nodes in the cluster if desired.
> Remove default node selector from template

- deploy/operator.yaml
- deployment/network-operator/README.md
- deployment/network-operator/templates/operator.yaml
- deployment/network-operator/values.yaml
- manifests/stage-nv-peer-mem-driver/0010_nv-peer-mem-driver-ds.yaml
- manifests/stage-ofed-driver/0010_ofed-driver-ds.yaml
- pkg/consts/consts.go
- pkg/state/state_nv_peer.go
- pkg/state/state_ofed.go
- pkg/utils/utils.go
Proxy settings will be provided to helm when the operator is installed. these should propagate to the operands created by the operator.
Fixes #23
> Support HTTP proxy setting to be passed down to containers

- manifests/stage-ofed-driver/0010_ofed-driver-ds.yaml
Latest official MOFED driver containers have changed
image fromat to:
mofed-<Branch Name>:<Version>-<OS Name><OS Version>-<CPU Arch>
e.g mofed-5.1-2:5.1-2.5.1.1-ubuntu18.04-x86_64
modify template and state ofed code to fit the new format.
- ofed-driver daemonset template
- Modify container image name
- Remove CPU arch from daemonset name and templates as it
is not required and kubernetes forbits _ in object names.
- state ofed driver: translate golang amd64 CPU Arch to x86_64
> Update state OFED with new container image name format

- README.md
- deployment/network-operator/README.md
- deployment/network-operator/values.yaml
- example/deploy/crds/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
This performs the following updates
- Update k8s-rdma-shared-dp to last release tag of v1.1.0
- Change Whereabouts IPAM CNI to point to the last release tag
of the upstream repository (github.com/dougbtv/whereabouts)
instead of openshift downstream repo
- README updates of the above and minor typo fix
- Edit deployment README and remove custom version from examples
- Add section to deployment README about NFD
- update nicclusterpolicy CR example with the versions
> Update components version and README

- manifests/stage-whereabouts-cni/0050-whereabouts-ds.yaml
hereabouts is IPAM plugin which should not depend on another cni to be deployed or deleted
> Make whereabouts daemonset use hostNetwork

- manifests/stage-rdma-device-plugin/0020-k8s-rdma-shared-dev-plugin-ds.yaml
Currently rdma resources "/dev/infiniband" are mounted by using hostNetwork, where rdma resources will not be tracked when kernel modules/drivers are installed after deploying rdma shared device plugin.
This patch mounts "/dev/infiniband" inside the container with volumes which keeps tracking the changes to "/dev/infiniband"
Fixes #31
> Mount /dev/inside rdma shared device plugin

- README.md
- deployment/network-operator/README.md
- deployment/network-operator/values.yaml
- example/deploy/crds/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
Due to Issue: https://github.com/intel/multus-cni/issues/592
When multus is removed from the cluster it is left in an inoperable
as CNI calls fail due to removed RBAC.
While it makes sense to occur for secondary network when specified
in a pod spec as net-attach-def name, it should not fail on primary
network.
Downgrade multus CNI to v3.4.1 where such an issue does not occur.
> Change default Multus CNI version

- deployment/network-operator/Chart.yaml
- deployment/network-operator/README.md
- deployment/network-operator/charts/sriov-network-operator/.helmignore
- deployment/network-operator/charts/sriov-network-operator/Chart.yaml
- deployment/network-operator/charts/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovibnetworks_crd.yaml
- deployment/network-operator/charts/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovnetworknodepolicies_crd.yaml
- deployment/network-operator/charts/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovnetworknodestates_crd.yaml
- deployment/network-operator/charts/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovnetworks_crd.yaml
- deployment/network-operator/charts/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovoperatorconfigs_crd.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/NOTES.txt
- deployment/network-operator/charts/sriov-network-operator/templates/_helpers.tpl
- deployment/network-operator/charts/sriov-network-operator/templates/clusterrole.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/clusterrolebinding.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/operator.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/role.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/role_binding.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/service_account.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/sriovnetwork.openshift.io_v1_sriovnetworknodepolicy_cr.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/sriovnetwork.openshift.io_v1_sriovoperatorconfig_cr.yaml
- deployment/network-operator/charts/sriov-network-operator/values.yaml
- deployment/network-operator/values.yaml
This commit adds Helm chart to sriov-network-operator.
- Add this chart as an optional dependency to the main
network-operator chart
- Add the needed chart files/crds/templates
- update README
> Support deploying SR-IOV network operator

- deployment/network-operator/charts/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovnetworknodepolicies_crd.yaml
NIC Device Mode cpould be set to  "legacy" or "switchdev" during
sriov-network-operator configuration.
Fixes: Issue #89
> Add 'eSwitchMode' flag support

- deployment/network-operator/charts/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovnetworks_crd.yaml
In order to generate a network attachment definition that chains the SR-IOV
CNI configuration with additional metaplugins (such as VRF, or firewall), we
expose a new MetaPluginsConfig where to put the json list of the extra configurations,
in the form of
{
// meta plugin A config
},
{
// meta plugin B config
}
metaPlugins param was introduces in sriov-network-operator in this
commit:
https://github.com/openshift/sriov-network-operator/commit/6a279015ed448cb61fa99f74f72dc837ae95df5e
> Add an optional SriovNetwork section: additional metaplugins

- scripts/delete-operator.sh
We can use 'make uninstall' to delete CRDs object. Let's do not drop
them during undeploy to make development smothier.
> Do not delete CRDs in 'undeploy' target

- deployment/network-operator/README.md
- deployment/network-operator/templates/tests/test-dev-plugin.yaml
- deployment/network-operator/templates/tests/test-rping.yaml
- deployment/network-operator/values.yaml
This PR bring 2 helm chart tests for network operator that tests device plugin resources and rping for deployment
> Add helm chart tests

- api/v1alpha1/macvlannetwork_types.go
- api/v1alpha1/nicclusterpolicy_types.go
- config/crd/bases/mellanox.com_macvlannetworks.yaml
- config/crd/bases/mellanox.com_nicclusterpolicies.yaml
This commit adds a `status` printer column which
reflects the global state of `NicClusterPolicy` and `MacvlanNetwork` CR instance.
Example:
```
$> kubectl get nicclusterpolicy
NAME                 STATUS
nic-cluster-policy   ready
```
> Add status printer column for custom resources

- manifests/stage-multus-cni/0050-multus-ds.yml
When deploying Multus secondary network, it generates config file
00-multus.conf which will be CNI config file, when Multus has
removed the config file and bin file will stay which leading to
use Multus even if the secondary network was deleted.
When Muluts is deleted also the permission will be deleted, thus
lead to failure in creating/removing any pod that uses CNI
including removing the network operator itself.
This commit fixes the issue deleting the config file generated by
multus
Fixes #74
> Remove multus generate config file when undeploy multus

- deployment/network-operator/templates/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- deployment/network-operator/values.yaml
Multus config 'secondaryNetwork.multus.config' is a string of json format, Helm has a behaviour of transforming string of json format json object instead of keeping it a string
This PR enforces string by using 'quote' helm rendering function
fixes #100
> helm deployment fail when setting multus config

- deployment/network-operator/charts/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovnetworknodestates_crd.yaml
- deployment/network-operator/charts/sriov-network-operator/values.yaml
Update sriov-network-operator crd to support switchdev and update operator and daemon images to be from harbor.mellanox
> Update sriov-network-operator crd and images

- deployment/network-operator/charts/node-feature-discovery/Chart.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/clusterrole.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/clusterrolebinding.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/master.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/nfd-worker-conf.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/worker.yaml
- deployment/network-operator/charts/node-feature-discovery/values.yaml
- deployment/network-operator/values.yaml
1. Use helm chart updated from NFD repo
2. network-operator specifies the latest build of the NFD
3. nfd-master '--instance' option is set to 'nvidia.networking' be default
> Update node-feature-discovery deployment

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/new-release.md
This commit adds templates for possible issues
that can be opened against Network Operator project
- Bug report template: To be used when reporting
a possible bug in network-operator
- Enhancement template: To be used when requesting
an enhancement/feature of network operator
- Release template: To be used when creating a new release
of network-operator. This includes a checklist of actions
that should be done in order to release a new version
of network-operator
> Add Issue templates

- .github/ISSUE_TEMPLATE/new-release.md
Update new release template to merge helm
index file into the existing one instead of
creating a new one each release
> Update new release template

- README.md
- deploy/operator-ns.yaml
- deploy/operator-resources-ns.yaml
- deploy/operator.yaml
- deploy/role.yaml
- deploy/role_binding.yaml
- deploy/service_account.yaml
- deployment/network-operator/README.md
- deployment/network-operator/templates/NOTES.txt
- deployment/network-operator/templates/operator-resources-ns.yaml
- deployment/network-operator/templates/role.yaml
- deployment/network-operator/templates/role_binding.yaml
- pkg/consts/consts.go
This commit modifies network operator namespaces
to be prefixed with `nvidia` instead of `mlnx`
In addition modify operator name in README to be
"nvidia network operator" instead of
"nvidia mellanox network operator" as that is its
marketing name.
> Modify network-operator namespaces

- README.md
- api/v1alpha1/nicclusterpolicy_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/mellanox.com_nicclusterpolicies.yaml
- deployment/network-operator/README.md
- deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml
- deployment/network-operator/templates/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- deployment/network-operator/templates/test-rdma-shared-dev-plugin.yaml
- deployment/network-operator/templates/tests/test-rping.yaml
- deployment/network-operator/values.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- pkg/state/state_shared_dp.go
Since we will allow configure and install SR-IOV Network Device Plugin
we need to have more user-friendly name to not confuse users with a
'devicePlugin' option.
> Rename 'devicePlugin' to 'rdmaSharedDevicePlugin'

- .github/ISSUE_TEMPLATE/bug-report.md
Commit b159be04a0b67c0e3cfddf510d3a128c4b330266 changed namespace
prefix from 'mlnx' to 'nvidia' so we need to adjust issue template
too.
> Update namespace name in bug template

- deployment/network-operator/charts/node-feature-discovery/values.yaml
the tolerations value is array therefore we need to pass
[] and not {}
> [helm] fix nfd worker tolerations value

- controllers/macvlannetwork_controller.go
- pkg/state/state_macvlan_network.go
- pkg/utils/utils.go
Objects SelfLink was deprecated in Kubernetes v1.16 and will be
removed in v.1.21. SelfLink is disabled by default in v.1.20.
This implementation is a simplified version of the original one [1]
and uses public API which isn't supposed to be changed soon.
This patch also moves MacvlanNetwork status update to controller.
[1] https://github.com/kubernetes/kubernetes/blob/54449be03127f883e52df48b95adef36925ae2cf/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/namer.go#L105
Closes: #133
Closes: #59
> Stop using SelfLink

- .travis.yml
- Dockerfile
- Makefile
This PR adds Hadolint (https://github.com/hadolint/hadolint) linter for Dockerfiles and `helm lint` call  to  Makefile and CI.
Also, fix some style issues detected by the linter in Dockerfile.
Closes #116 
Closes #115
> Add linters for helm charts and Dockerfiles

- Makefile
Change helm installation method. Use get_helm.sh script instead of downloading a tarball.
> Fix error in lint-helm target in Makfile

- manifests/stage-nv-peer-mem-driver/0010_nv-peer-mem-driver-ds.yaml
We use `nvidia.com/gpu.present: "true"` label to select nodes on which we should deploy nv-peer-mem-driver POD. NFD manages this label, and it set label based on GPU PCI device presence. With current network-operator behavior, we can deploy `nv-peer-mem-driver` POD on nodes with no GPU driver, which will cause a crash of `nv-peer-mem-driver` POD.
The recent version of GPU operator put 'nvidia.com/gpu.count' label
on a node after initialization of GPU driver finished on it.
We can understand that node has GPU and GPU driver already deployed
on it by checking this label.
> Add additional nodeAffinity for nv-peer-mem-driver POD

- manifests/stage-nv-peer-mem-driver/0010_nv-peer-mem-driver-ds.yaml
- pkg/state/state_nv_peer.go
Autoselect right path of OFED src for nv-peer-mem POD
Based on the fact that Mellanox OFED driver POD is deployed or not,
network-operator will select the right OFED src path for nv-peer-mem POD.
If OFED driver POD doesn't exist, OFED from the host will be used.
~~Add additional option `nvPeerDriver.ofedDriverSourcePath` to
NicClusterPolicy CR. Default value points to the location
in which `Mellanox OFED driver` POD will install the driver.
If the option set to an empty string, then Mellanox OFED driver
from the host OS will be used~~
Fixes #76
> Add support for host OFED to peer-mem POD

- .github/ISSUE_TEMPLATE/new-release.md
- scripts/releases/prepare-release.sh
- scripts/releases/update-gh-pages.sh
This script updates chart version and creates helm package.
Related: #131
> Add 'prepare-release.sh' script

- pkg/state/factory.go
Getting Multus, CNI plugins and Whereabouts deployed befor OFED and
device plugins makes networking usable even if drivers are not
deployed by any reason.
> Change order of networking components rendering

- manifests/stage-ofed-driver/0010_ofed-driver-ds.yaml
OFED POD tries to unload drivers kernel module when it receives SIGTERM. If the driver unloading procedure doesn't complete, there can be some unwanted loaded modules and other leftovers on the host after OFED POD termination. Unloading can take more time than the default terminationGracePeriodSeconds. Increase terminationGracePeriodSeconds for OFED POD to grant it additional time for unloading procedure to complete.
Testing in my ENV shows that complete OFED unloading takes ~ 40 sec.
In failed CI runs where we detect "unwanted" modules on host, there are multiple messages in docker log file.
```
Container 3847c06f1fd2c94b43257a75023e44e0c90dda4691b7e80cbe6ca25792f39ddc failed to exit within 30 seconds of signal 15 - using the force
```
This means that OFED POD was killed before it …
> Increase terminationGracePeriodSeconds for OFED POD

- deployment/network-operator/charts/sriov-network-operator/values.yaml
> Use Kubernetes-specific image for SR-IOV Network operator by default

- manifests/stage-rdma-device-plugin/0060_rdma-shared-dev-plugin-ds.yaml
- manifests/stage-sriov-device-plugin/0030-sriov-dp-daemonset.yml
- pkg/state/state_shared_dp.go
- pkg/state/state_sriov_dp.go
Both SR-IOV Device Plugin and RDMA Shared Device Plugin should
wait until OFED container is started if it's supposed to be
deployed.
During cluster scale-up Kubernetes schedules DaemonSet to new nodes
and we don't configure an order of pods in this case. To wait until
MOFED containder is ready we'll add initContainer with the same logic
as MOFED container has.
This will prevent us to run device plugin before MOFED started during
scale-up but it doesn't fix an issue if node was rebooted.
> Add initContainers for device plugins

- controllers/nicclusterpolicy_controller.go
- deploy/role.yaml
- deployment/network-operator/templates/role.yaml
- manifests/stage-ofed-driver/0050_ofed-driver-ds.yaml
- manifests/stage-rdma-device-plugin/0060_rdma-shared-dev-plugin-ds.yaml
- manifests/stage-sriov-device-plugin/0030-sriov-dp-daemonset.yml
- pkg/nodeinfo/attributes.go
Operator will add nvidia.com/ofed.wait=true label to node,
so device plugins pods (SR-IOV Device Plugin, RDMA Shared
Device Plugin) won't be cheduled to these nodes. All running
device plugins pods will be terminated.
Once OFED reach Running state nodes will have
nvidia.com/ofed.wait=false label, to allow Kubernetes schedule
device plugins pods to these nodes.
In case if OFED deployment is disabled label
nvidia.com/ofed.wait=false will be added to the nodes.
This patch will fix an issue with pods initializing orded after
node reboot.
> Use labels to wait for MOFED pods

- .github/ISSUE_TEMPLATE/bug-report.md
Based on #174 it's good to ask users to provide a bit more
information in bug reports:
- Network Operator version
- Kubernetes' nodes information (labels, annotations and status)
> Update bug report template

- controllers/nicclusterpolicy_controller.go
We don't need to check for container status if there is no running
containers inside MOFED pod.
Closes #182
> Fix MOFED pod status check

- manifests/stage-nv-peer-mem-driver/0050_nv-peer-mem-driver-ds.yaml
- pkg/state/manager.go
We manage deployment order in a manager only for NicClusterPolicy now.
It's not needed anymore since we use labeling mechanism to wait until
MOFED will be deployed.
There should not be any issues for parallel deployment of networking
stack (CNI plugins, Multus, Whereabouts, etc) and MOFED because they
don't depend on each other.
This patch improves deployment speed on a large environment and fixes
an issue if one MOFED pod block any other deployment on the other nodes.
Closes: #184
> Do not wait state group deployment in manager

- README.md
- manifests/stage-nv-peer-mem-driver/0050_nv-peer-mem-driver-ds.yaml
- pkg/nodeinfo/attributes.go
- pkg/nodeinfo/filter.go
- pkg/nodeinfo/filter_test.go
- pkg/state/state_nv_peer.go
This rule prevents driver from deploying on node
which has NVIDIA GPU driver with version >= 465.
Starting from v465 NVIDIA GPU driver includes a built-in nvidia_peermem
module which is a replacement for nv_peer_mem module.
NVIDIA GPU operator manages nvidia_peermem module loading.
> Add additional nodeAffinity rule for nv-peer-mem-driver POD

- manifests/stage-ofed-driver/0050_ofed-driver-ds.yaml
We need to mount host's /etc and /lib/udev into the pod co work
with the latest https://github.com/Mellanox/ofed-docker.
> Update MOFED container volumes

- deployment/network-operator/README.md
We don't have '-alpha' and '-beta' versions now so we don't need
to add '--devel' flag to install Network Operator chart.
> Remove '--devel' from 'helm install' command

- Dockerfile
- Makefile
- README.md
Image size changed from 346MB to 50.3MB
> Set alpine:latest as a base image by default

- deployment/network-operator/values.yaml
Networking-related images are used from ghcr.io/k8snetworkplumbingwg
repository now.
There is no new community release for sriov-network-device-plugin yet,
so the latest tagged image is used.
> Update networking images

- manifests/stage-whereabouts-cni/0010-whereabouts.cni.cncf.io_ippools.yaml
The beta CustomResourceDefinition API (apiextensions.k8s.io/v1beta1)
is removed on Kubernetes v1.22, so we should not use it anymore.
Closes: #230
> Use stable extension API for CRDs

- manifests/stage-whereabouts-cni/0010-whereabouts.cni.cncf.io_ippools.yaml
Commit 278613dea3cf054c4ea6a7cd62aed829ac709269 breaks CRD deployment.
This patch fixes the issue by syncing CRD with upstream version.
> Sync ippools.whereabouts.cni.cncf.io CRD with upstream

- deployment/network-operator/templates/operator.yaml
Network Operator has different format for imagePullSecrets
rather than other components. This patch fixes it.
Upgrade notice: you need to update your values.yaml file
manuallty if you use imagePullSecrets with old format.
> Fix imagePullSecrets for Network Operator

- deployment/network-operator/README.md
mutlus -> multus
Signed-off-by: Chad Dougherty <crd@acm.org>
> fix trivial typo

- pkg/state/state_sriov_dp.go
Panic may happen when sriov-device-plugin deployed
and there are no nodes with
`feature.node.kubernetes.io/pci-15b3.present` label in
the cluster
Fixes #267 
> Fix panic in stateSriovDP.GetWatchSources

- manifests/stage-ofed-driver/0050_ofed-driver-ds.yaml
updateStrategy for OFED DaemonSet changed to "OnDelete"
If OnDelete update strategy is used and DaemonSet template
updated then new DaemonSet pods will only be created when you
manually delete old DaemonSet pods.
If affinity rule or nodeSelector changed, PODs will be added
or removed automatically.
This change is required to be able to implement a rolling upgrade
for environments with the containerized driver.
Steps to apply driver upgrade:
1. Update OFED DaemonSet with new image version (this will not
trigger automatic PODs removal and driver reloading)
2. Remove PODs with secondary network from some set of nodes
3. Manually delete OFED PODs from nodes that have no
PODs with secondary networking.
> Change updateStrategy for OFED DaemonSet

- manifests/stage-ofed-driver/0050_ofed-driver-ds.yaml
We need to be able to get host OS version from pod to install
correct versions of packages during driver deployment.
/usr directory is needed because /etc/os-release file is a symlink:
/etc/os-release -> ../usr/lib/os-release
> Mount host /usr directory to MOFED pod

- manifests/stage-hostdevice-network/0010-hostdevice-net-cr.yml
- pkg/state/state_hostdevice_network.go
- pkg/state/state_hostdevice_network_test.go
Currently network operator doesn't allow deploying host device networks if the resource name start with "nvidia.com" prefix. The solution is to normalize all resource names for hostdevicenetwork state to start with a common prefix.
> Accept resource names for hostdevicenetwork either with or without prefix

- controllers/nicclusterpolicy_controller.go
This fixes the issue with mofed.wait label not being set to false when other issues in deployment occur
The proposed solution is to update node labels regardless of state sync status
> Update node labels regardless of state sync status

- deployment/network-operator/README.md
- deployment/network-operator/templates/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
Currently the SR-IOV Device Plugin resource definition can only select devices based on vendor ID. This creates problems in heterogeneous cluster deployments.
The proposed solution is to support all selectors from sriov-device-plugin.
The fix is intentionally aligned with the current implementation and not made more generic as that would require changing `values.yaml` and ensuring backwards compatibility with different versions of network-operator
> Support extended selectors for sriov-device-plugin with helm deployment

- deployment/network-operator/README.md
- deployment/network-operator/values.yaml
In VM environments we see it can take up to 12 minutes
to complete driver compilation. Increase default stratup probe
retry period to 20s to allow for a total of 20 min before moving
the pod to failed state
> Change default startup probe time for ofed driver

- Dockerfile
- Makefile
Adding labels to container image to enhance debuggability.
```bash
$ skopeo inspect docker://quay.io/frollandnvidia/network-operator:test | jq .Labels
{
"architecture": "x86_64",
"build-date": "2022-03-15T12:36:09UTC",
"com.redhat.build-host": "cpt-1002.osbs.prod.upshift.rdu2.redhat.com",
"com.redhat.component": "ubi8-micro-container",
"com.redhat.license_terms": "https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI",
"description": "NVIDIA Network Operator",
"distribution-scope": "public",
"io.buildah.version": "1.23.1",
"io.k8s.description": "NVIDIA Network Operator",
"io.k8s.display-name": "NVIDIA Network Operator",
"io.openshift.expose-services": "",
"maintainer": "NVIDIA nvidia-network-operator-support@nvidia.com",
"name": "NVIDIA Network Operator", …
```
> Add labels to container image

- deployment/network-operator/Chart.yaml
- deployment/network-operator/charts/sriov-network-operator/.helmignore
- deployment/network-operator/charts/sriov-network-operator/Chart.yaml
- deployment/network-operator/charts/sriov-network-operator/README.md
- deployment/network-operator/charts/sriov-network-operator/crds/k8s.cni.cncf.io_networkattachmentdefinitions_crd.yaml
- deployment/network-operator/charts/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovibnetworks.yaml
- deployment/network-operator/charts/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovnetworknodepolicies.yaml
- deployment/network-operator/charts/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovnetworknodestates.yaml
- deployment/network-operator/charts/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovnetworkpoolconfigs.yaml
- deployment/network-operator/charts/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovnetworks.yaml
- deployment/network-operator/charts/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovoperatorconfigs.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/NOTES.txt
- deployment/network-operator/charts/sriov-network-operator/templates/_helpers.tpl
- deployment/network-operator/charts/sriov-network-operator/templates/clusterrole.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/clusterrolebinding.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/configmap.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/operator.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/role.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/rolebinding.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/serviceaccount.yaml
- deployment/network-operator/charts/sriov-network-operator/values.yaml
To fix [1] we need to use internal version of the SR-IOV Network
Operator chart until there will be a new release.
[1] https://github.com/k8snetworkplumbingwg/sriov-network-operator/issues/267
> Add SR-IOV Network Operator chart into the Network Operator repo

- bundle/manifests/nvidia-network-operator.clusterserviceversion.yaml
- config/manifests/bases/nvidia-network-operator.clusterserviceversion.yaml
The `MultiNamespace` is making the Network Operator CSV installed in all namespaces.
Updates configuration to `OwnNamespace` and `SingleNamespace`, similar to GPU Operator.
> Change OLM installModes to SingleNamespace

- example/sriov-network/sriov-network-node-policy-switchdev.yaml
The resource name in the SRIOV switchdev example was not valid according to:
https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/v3.4.0/pkg/utils/utils.go#L274
> Fix SRIOV switchdev example

- deployment/network-operator/README.md
- deployment/network-operator/values.yaml
Macvlan Network with RDMA Shared Device Plugin should be deployed
by default.
HostDevice Network is be disabled in the default configuration now.
> Do not deploy SR-IOV Device Plugin by default

- deployment/network-operator/Chart.yaml
- deployment/network-operator/values.yaml
The latest GPU Operator uses NFD v0.10.1 so it's goot to keep
versions synced
Closes: #325
> Bump NFD version to v0.10.1

- deploy/operator.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/operator.yaml
- deployment/network-operator/charts/sriov-network-operator/values.yaml
- deployment/network-operator/values.yaml
- manifests/stage-container-networking-plugins/0010-container-networking-plugins-ds.yml
- manifests/stage-multus-cni/0050-multus-ds.yml
- manifests/stage-nv-peer-mem-driver/0050_nv-peer-mem-driver-ds.yaml
- manifests/stage-ofed-driver/0050_ofed-driver-ds.yaml
- manifests/stage-rdma-device-plugin/0060_rdma-shared-dev-plugin-ds.yaml
- manifests/stage-sriov-device-plugin/0030-sriov-dp-daemonset.yml
- manifests/stage-whereabouts-cni/0050-whereabouts-ds.yaml
with Kubernetes 1.24, master nodes are now
labeld and tainted as `node-role.kubernetes.io/control-plane`
Support this in Network operator by:
- Extending tolerations in relevant deployment files
- adjusting node affinity in relevant deployment files
> Update YAMLs to support k8s (kubeadm) new control-plane labels

- .github/workflows/build.yml
- .gitignore
- .golangci.yml
- Dockerfile
- Makefile
- controllers/nicclusterpolicy_controller.go
- go.mod
- go.sum
- pkg/render/render.go
- pkg/state/fake_manager.go
- pkg/upgrade/node_upgrade_state_provider.go
- pkg/upgrade/util.go
This commit bumps go version to 1.18
as a result several changes were needed
- modify Makefile to support go install
- bump golangci lint as the current version did
not support go 1.18
- update golangci yaml and remove deprecated linters
- update Dockerfile
- Address golangci issues discovered after version bump
- update go.mod (run go mod tidy)
In addition Perform some cleanups in Makefile
mainly getting rid of .gopath folder as it is not
really needed and causes issues when working with some
IDEs
> Bump go to 1.18 And Makefile cleanup

- bundle/manifests/nvidia-network-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
This update fixes default images in alm-examples to work
out of the box during installation using OCP UI.
> Update OCP bundle to v1.2.1

- go.mod
- go.sum
- manifests/stage-ofed-driver/0050_ofed-driver-ds.yaml
- pkg/state/state_ofed.go
- pkg/state/state_ofed_test.go
- pkg/state/state_suite_test.go
starting with MOFED driver version  5.7
the mofed driver container image name format
will change from:
`<image-repo>/<image-name>-<driver-ver>:<os-name><os-ver>-<cpu-arch>`
to:
`<image-repo>/<image-name>:<driver-ver>-<os-name><os-ver>-<cpu-arch>`
- Support both formats depending on the driver version
in state ofed.
- Add unit test for the newly added logic
> Update MOFED driver image format

- Makefile
Existing timeout (15s) is too low and tests are periodically
panic.
> Increase default timeout for tests

- config/manager/manager.yaml
- deploy/operator.yaml
- deployment/network-operator/templates/operator.yaml
- pkg/upgrade/consts.go
- pkg/upgrade/upgrade_state.go
- pkg/upgrade/upgrade_state_test.go
We want to skip network-operator itself during the drain because the upgrade process might hang if the operator is evicted and can't be rescheduled to any other node, e.g. in a single-node cluster.
It's safe to do because the goal of the node draining during the upgrade is to evict pods that might use MOFED and network-operator doesn't use in its own pod.
> Skip network-operator pod when draining nodes during OFED upgrade

- api/v1alpha1/nicclusterpolicy_types.go
- config/crd/bases/mellanox.com_nicclusterpolicies.yaml
- deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml
Add minimum validation for Ofed Upgrade parameters
in NicClusterPolicy CRD. (TimeoutSecond, MaxParallelUpgrades)
> Add minimum validation for Ofed upgrade

- deployment/network-operator/README.md
- deployment/network-operator/templates/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- deployment/network-operator/values.yaml
fix: Add field in the nicclusterpolicy helm template to allow setting the nodeAffinity field
related issue: https://github.com/Mellanox/network-operator/issues/310
> fix: Add field in the nicclusterpolicy helm template for nodeAffinity

- controllers/upgrade_controller.go
In the auto upgrade flow, the upgrade state of the nodes is built
based on the Ofed pods.
However, there can be a stage where pods are not available as
the Upgrade flow is deleting them and new ones were not created
yet.
In that case, the corresponding node will not be considered in the
upgrade logic at this specific time when the pod is not re-created.
This can affect the "MaxParallelUpgrades" feature.
With this commit, in case a Ofed DaemonSet has one or more unavailable
pods, the upgrade logic will not run and the notification will be requeue
to be handle later.
> Requeue if pod not available in AutoUpgrade

- pkg/upgrade/upgrade_state.go
In MOFED upgrade flow, add "uncordon-required" count
in state print.
> Add Uncordon state in print

- controllers/upgrade_controller.go
In case that the DaemonSet DesiredNumberScheduled is
different than the number of pods, requeue.
> Fix condition on MOFED upgrade

- bundle/manifests/nvidia-network-operator.clusterserviceversion.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml
We need to set deleteEmptyDir=true and force=true for node draining
settings to work with default OCP installation.
> Update OCP deployment examples with OFED upgradePolicy

- api/v1alpha1/nicclusterpolicy_types.go
- bundle/manifests/nvidia-network-operator.clusterserviceversion.yaml
- config/crd/bases/mellanox.com_nicclusterpolicies.yaml
- config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml
- deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml
- deployment/network-operator/templates/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- deployment/network-operator/values.yaml
- docs/automatic-ofed-upgrade.md
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml
When attempting to drain a node, a non-fatal error might occur and the drain library will retry the action which caused this error in a few seconds (for example, evicting the pod violates the deployment's disruption budget).
If the error's cause is not fixed, there will be infinite retries unless the drain is terminated by timeout.
Since drain operation is disruptive and makes the node unschedulable, introducing the default timeout to avoid taking the node out of action indefinitely.
Signed-off-by: Alexander Maslennikov<amaslennikov@nvidia.com>
> Set a default timeout for node drain in OFED auto-upgrade config

- deployment/network-operator/README.md
- deployment/network-operator/values.yaml
ib-kubernetes:v1.0.2 contains this fix: https://github.com/Mellanox/ib-kubernetes/pull/92
> Upgrade ib-kubernetes to v1.0.2

- controllers/nicclusterpolicy_controller.go
- controllers/predicate.go
- controllers/upgrade_controller.go
We need to watch for node create event for correct cluster scale up by adding 'network.nvidia.com/operator.mofed.wait' label.
> Watch for node label change event in NicClusterPolicy reconcile loop

- deployment/network-operator/templates/role.yaml
The kube client used in the Network Operators seems to perfom Watch operations on the resources. If the `watch` permission isn't provided, the pod logs get inundated with the following errors:
```
reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1beta1.PodSecurityPolicy: unknown (get podsecuritypolicies.policy)
```
> update psp permissions in clusterrole

- manifests/stage-ofed-driver/0050_ofed-driver-ds.yaml
/lib/modules is required to re-load original driver on OFED container termination.
> Mount host /lib/modules directory to OFED container

- api/v1alpha1/nicclusterpolicy_types.go
- bundle/manifests/mellanox.com_nicclusterpolicies.yaml
- bundle/manifests/nvidia-network-operator.clusterserviceversion.yaml
- config/crd/bases/mellanox.com_hostdevicenetworks.yaml
- config/crd/bases/mellanox.com_ipoibnetworks.yaml
- config/crd/bases/mellanox.com_macvlannetworks.yaml
- config/crd/bases/mellanox.com_nicclusterpolicies.yaml
- config/rbac/role.yaml
- config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml
- deployment/network-operator/README.md
- deployment/network-operator/crds/mellanox.com_hostdevicenetworks.yaml
- deployment/network-operator/crds/mellanox.com_ipoibnetworks.yaml
- deployment/network-operator/crds/mellanox.com_macvlannetworks.yaml
- deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml
- deployment/network-operator/templates/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- deployment/network-operator/values.yaml
- manifests/stage-ofed-driver/0050_ofed-driver-ds.yaml
Adding to NicClusterPolicy CRD the possibility to specify the termination grace period for the Mofed container. The default is 300 seconds.
It is also configurable in Helm values file.
> Add Mofed termination grace period param

- manifests/stage-ib-kubernetes/0070-deployment.yaml
We want to schedule ib-kubernetes pod onto the control plane, so in order to pass the control-plane taint, we need to add a corresponding toleration to the deployment spec
> Add control-plane toleration for ib-kubernetes

- deployment/network-operator/values.yaml
This image contains an important fix
https://github.com/k8snetworkplumbingwg/ib-sriov-cni/pull/67 We need to incorporate this fix in the next netOp release
> Update ib-sriov-cni image version to the current latest master commit

- deployment/network-operator/charts/sriov-network-operator/templates/sriovnetworknodepolicy.yaml
The owner of SR-IOV Device Plugin daemonset is default policy so it will be deleted both with a defaut during helm uninstall procedure.
> Deploy default SriovNetworkNodePolicy by helm chart

- manifests/stage-ib-kubernetes/0070-deployment.yaml
When RollingUpdate strategy is used, the old pod is only deleted when the new pod gets to the running state, to reduce the downtime. https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/
However, for ib-kubernetes we specified the anti affinity, which prevent two ib-kubernetes pods running on the same node. In this case, when the deployment is updated, the new pod is forever pending because the old one is not deleted.
To fix this, changing the update strategy to Recreate.
> Change ib-kubernetes update strategy to Recreate

- Makefile
- config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
- hack/release.go
- hack/release.yaml
- hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.template
- hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
- hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.template
- hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml
- hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.template
- hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml
- hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.template
- hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- hack/templates/samples/mellanox.com_v1alpha1_nicclusterpolicy.template
- hack/templates/values/values.template
New make target changes Network Operator and MOFED images data in examples, helm chart and OCP bundle.
Simple golang binary is used instead of kustomize to minimize support effort.
> Add release-build make target

- controllers/nicclusterpolicy_controller.go
- controllers/nicclusterpolicy_controller_test.go
- controllers/suite_test.go
- deployment/network-operator/templates/role.yaml
- pkg/consts/consts.go
- pkg/state/state_cni_plugins.go
- pkg/state/state_ib_kubernetes.go
- pkg/state/state_ipoib_cni.go
- pkg/state/state_multus_cni.go
- pkg/state/state_nv_peer.go
- pkg/state/state_ofed.go
- pkg/state/state_pod_security_policy.go
- pkg/state/state_shared_dp.go
- pkg/state/state_skel.go
- pkg/state/state_sriov_dp.go
- pkg/state/state_whereabouts_cni.go
In case the user deletes a subsection of the
NicClusterPolicy, created resources needs to be deleted.
The state of the stage will be `notReady` until all resources are deleted. Then it will move to `ignore`.
> Support delete of resources

- deployment/network-operator/values.yaml
Signed-off-by: Shiva Krishna, Merla <smerla@nvidia.com>
> Set maxParallelUpgrades as 1 by default to be least disruptive.

- api/v1alpha1/utils.go
no need to copy the object on the stack,
a reference will suffice.
> Use reference instead of value in utils

- deployment/network-operator/README.md
- deployment/network-operator/templates/sriovnetwork.openshift.io_sriovoperatorconfig.yaml
- deployment/network-operator/values.yaml
This option allows to configure nodeSelector
for sriov-network-operator daemon
Examples:
**Defaults**
```
helm template -n test  --set sriovNetworkOperator.enabled=true  . | grep -A 30 SriovOperatorConfig
kind: SriovOperatorConfig
metadata:
name: default
namespace: test
spec:
enableInjector: false
enableOperatorWebhook: false
configDaemonNodeSelector:
beta.kubernetes.io/os: linux
network.nvidia.com/operator.mofed.wait: "false"
node-role.kubernetes.io/worker: ""
```
**unset  node-role.kubernetes.io/worker: ""**
```
helm template -n test     --set sriovNetworkOperator.enabled=true --set sriovNetworkOperator.configDaemonNodeSelectorExtra."node-role\.kubernetes\.io/worker"=null  . | grep -A 30 SriovOperatorConfig
kind: SriovOperatorConfig
metadata:
name: default
namespace: test
spec: …
```
> Add sriovNetworkOperator.configDaemonNodeSelector to Helm values

- .github/workflows/build.yml
- Dockerfile
- Makefile
- controllers/hostdevicenetwork_controller.go
- controllers/ipoibnetwork_controller.go
- controllers/macvlannetwork_controller.go
- controllers/nicclusterpolicy_controller.go
- go.mod
- go.sum
- pkg/nodeinfo/node_info_test.go
- pkg/state/fake_manager.go
- pkg/state/fake_state.go
- pkg/state/state_cni_plugins.go
- pkg/state/state_multus_cni.go
- pkg/state/state_pod_security_policy.go
- pkg/state/state_sriov_dp_test.go
- pkg/state/state_whereabouts_cni.go
This PR include two related commits:
[Update golang to 1.20](https://github.com/Mellanox/network-operator/commit/303673d7937cc1d85701e3abe47b4e851b43d756)
[Update golangci lint to v1.52.2 and fix discovered problems](https://github.com/Mellanox/network-operator/commit/9f845ce815b1b0e72d0a60fa79127bc104fd0ba0)
closes https://github.com/Mellanox/network-operator/issues/456
> Update golang to 1.20

- main.go
- pkg/consts/consts.go
- pkg/state/state_skel.go
Replace Update call (replace) to k8s API with server-side apply call to preserve fields which were set in runtime.
Fixes an issue with never ending synchronization
on k8s > 1.25
related issue #482
> Use server-side apply to update objects

- controllers/nicclusterpolicy_controller.go
- controllers/predicate.go
- main.go
- pkg/consts/consts.go
- pkg/state/state_skel.go
This PR reverts https://github.com/Mellanox/network-operator/pull/481
server-side apply may be problematic when we try to upgrade network-operator version
The new version of the operator may not clean fields set by the previous release.
Proposed solution: keep existing Create/Update logic for resource and fix for https://github.com/Mellanox/network-operator/issues/482 in a different way - try to ignore updates of the object if the content (excluding resourceVersion of the object and managedFileds) is the same.
> Revert "server-side apply" patch and apply new fix for never-ending sync loop issue

- deployment/network-operator/templates/sriovnetwork.openshift.io_sriovoperatorconfig.yaml
If helm value sriovNetworkOperator.configDaemonNodeSelectorExtra map is manually
removed from the default values.yaml, then
wrong type for value error may occur while deploying helm chart.
> Set sriovNetworkOperator node selector in a helm chart in a safer manner

- config/rbac/role.yaml
- deployment/network-operator/templates/role.yaml
Common driver upgrade lib now uses controller revision hashes of daemon sets and pod to determine whether the driver on the node requires upgrade.
Adding the permission to get them for network-operator's cluster role
https://github.com/NVIDIA/k8s-operator-libs/commit/80ee54959934887f5f478ef80ed995938f94250b
> Allow network-operator to list controllerrevisions

- bundle/manifests/nvidia-network-operator.clusterserviceversion.yaml
- config/manager/manager.yaml
- deploy/operator.yaml
- deployment/network-operator/templates/operator.yaml
Fix for https://github.com/Mellanox/network-operator/issues/496
When the upgrade functionality was extracted into a separate upgrade library, the pod label for skipping drain was changed (https://github.com/NVIDIA/k8s-operator-libs/blob/89451d4d7524278f985a7e813d654084c9e5d146/pkg/upgrade/consts.go#L23). The operator's spec was not aligned to use this new label.
This label is required for the operator, when deployed on a single-node cluster, where operator runs on the same node as the ofed driver container. Without this label, the operator pod would drain itself, thus breaking the complete network-operator deployment.
With this label, the pod is omitted during the drain (https://github.com/NVIDIA/k8s-operator-libs/blob/89451d4d7524278f985a7e813d654084c9e5d146/pkg/upgrade/upgrade_state.go#L …
> Align the skip-drain label for the operator with the common upgrade lib

- config/rbac/role.yaml
- controllers/upgrade_controller.go
The previous PR https://github.com/Mellanox/network-operator/pull/490 didn't contain a fix for the openshift clusters
> Allow network-operator to list controllerrevisions in openshift

- manifests/stage-whereabouts-cni/0050-whereabouts-ds.yaml
Increase memory and cpu limits for whereabouts DaemonSet.
This required to prevent failure of whereabouts
pod with "out of memory" error on some
environments.
fixes #517
> Increase memory and cpu limits for whereabouts DaemonSet.

- Dockerfile
- deployment/network-operator/README.md
- deployment/network-operator/templates/upgrade-crd.yaml
- deployment/network-operator/values.yaml
This MR contains two changes:
1. Add CRDs for network-operator and sriov-network-operator to network-operator image
2. Add helm pre-upgrade hook to automatically apply CRDs
> Add support for CRD upgrade with Helm pre-upgrade hook

- Dockerfile
- deployment/network-operator/README.md
- deployment/network-operator/templates/upgrade-crd.yaml
- deployment/network-operator/values.yaml
Cherry pick from master to support upgrade of crds via helm chart
> V23.5.x add support for upgrading crds via Helm Hooks

- hack/templates/values/values.template
- pkg/state/manager.go
we should log error if it happend regardless
of SyncState.
> Log error in state manager

- deployment/network-operator/values.yaml
- hack/release.go
- hack/release.yaml
- hack/templates/values/values.template
cherry pick of nv-ipam support from v23.1.x-nv-ipam branch did not contain this templates alignment.
while the one from master did.
align templates and template generation for this branch.
> Align templates and generate files

- deployment/network-operator/README.md
- deployment/network-operator/templates/upgrade-crd.yaml
This required to handle use-case when network-operator upgrade is performed as:
step 1. uninstall an old version
step 2. install a new version
> Run CRD upgrade hook on helm chart install

- deployment/network-operator/README.md
- deployment/network-operator/templates/upgrade-crd.yaml
This required to handle use-case when
network-operator upgrade is performed as:
step 1. uninstall an old version
step 2. install a new version
(cherry picked from commit 3eea75a3b980cbedb0f46ae062409d9efcb307e3)
> [v23.5.x] Run CRD upgrade hook on helm chart install

- deployment/network-operator/templates/_helpers.tpl
- deployment/network-operator/templates/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- deployment/network-operator/templates/operator.yaml
- deployment/network-operator/templates/upgrade-crd.yaml
- deployment/network-operator/values.yaml
- hack/templates/values/values.template
To be able to use server-side apply YAML spec
should not contain "null" values
Changes:
- quote strings without default to always include a empty string value
- use empty list for imagePullSecrets field if secrets are not configured
Fixes #452 
Example of generated NicClusterPolicy
```
apiVersion: mellanox.com/v1alpha1                                                                                                                                                                                                                                                                                                [101/7155]
kind: NicClusterPolicy …
```
> Fix helm chart to generate correct NicClusterPolicy

- controllers/predicate.go
Predicate now will ignore following fields for Deployment obj:
- metadata.generation
- status.observedGeneration
- metadata.annotations["deployment.kubernetes.io/revision"]
(cherry picked from commit b7ab849d237d4da990154980723e4bd2536a9b4c)
> [v23.5.x] Improve IgnoreSameContentPredicate to handle Deployment obj correctly

- pkg/state/state_multus_cni.go
- pkg/state/state_nv_ipam_cni.go
- pkg/state/state_shared_dp.go
- pkg/state/state_sriov_dp.go
Currently config map changes will not trigger reconcile. Add ConfigMap as watched resource for nicclusterpolicy controller using nv-ipam state.
> Watch ConfigMap changes for related states

- Dockerfile
- README.md
- deployment/network-operator/Chart.yaml
- deployment/network-operator/charts/node-feature-discovery/.helmignore
- deployment/network-operator/charts/node-feature-discovery/Chart.yaml
- deployment/network-operator/charts/node-feature-discovery/README.md
- deployment/network-operator/charts/node-feature-discovery/crds/nfd-api-crds.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/_helpers.tpl
- deployment/network-operator/charts/node-feature-discovery/templates/cert-manager-certs.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/cert-manager-issuer.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/clusterrole.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/clusterrolebinding.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/master.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/nfd-master-conf.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/nfd-topologyupdater-conf.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/nfd-worker-conf.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/role.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/rolebinding.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/service.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/serviceaccount.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/topology-gc.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/topologyupdater-crds.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/topologyupdater.yaml
- deployment/network-operator/charts/node-feature-discovery/templates/worker.yaml
- deployment/network-operator/charts/node-feature-discovery/values.yaml
- deployment/network-operator/templates/upgrade-crd.yaml
- deployment/network-operator/values.yaml
- hack/templates/values/values.template
This Patch:
- Enhance READE NFD documentation
- Updates NFD Chart to V0.13.2
- Sync nfd values at `Values.yaml` with those in the GPU-Operator
> Sync NFD Helm Charts and config with the GPU-Operator

- README.md
- deployment/network-operator/values.yaml
- hack/templates/values/values.template
…namespace
This patch does the following:
- Set enableNodeFeatureApi to true by default
- Run the NFD with default annotation namespace
- Enhance READE NFD documentation
> Enable NodeFeatureApi in NFD

- README.md
- config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml
- deployment/network-operator/README.md
- deployment/network-operator/templates/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- deployment/network-operator/values.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.template
- hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.template
- hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.template
- hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.template
- hack/templates/samples/mellanox.com_v1alpha1_nicclusterpolicy.template
- hack/templates/values/values.template
There us hardware limitation of 128 GIDs per port in RocE mode. Since RocE v1 and v2 are enabled by default we have to limit to 63 devices per port to be allocated to workloads.
There is no such limitation for IPoIB mode, so user should update default value if needed.
This commit also makes rdmaHcaMax configurable via helm values.
> Limit maximum number of RDMA resources for Shared Device Plugin

- docs/mofed-container-env-vars.md
There is no need to document such env variables,
In addition Add a clarification on what "Experimental" environment variable mean.
> Remove Internal Environment variables from MOFED docs

- manifests/state-rdma-device-plugin/0060_rdma-shared-dev-plugin-ds.yaml
- manifests/state-sriov-device-plugin/0030-sriov-dp-daemonset.yml
There is no need to mount the whole '/var/lib/kubelet/' directory into a pod. It's enough to mount only '/var/lib/kubelet/device-plugins' and '/var/lib/kubelet/plugins_registry' directories.
> Update device plugins volumes mounts

- config/manager/kustomization.yaml
- config/rbac/role.yaml
- controllers/hostdevicenetwork_controller.go
- controllers/ipoibnetwork_controller.go
- controllers/macvlannetwork_controller.go
- controllers/nicclusterpolicy_controller.go
- controllers/upgrade_controller.go
Remove wildcards from mellanox.com and cni.cncf.k8s.io API groups, use explicit objects instead.
Fixes #595
> Tighten up controller roles

- deployment/network-operator/templates/upgrade-crd.yaml
Align tolerations, nodeSelector and affinity rules  with the network-operator Pod
> Add tolerations, nodeSelector and affinity rules to upgrade CRD job

- controllers/nicclusterpolicy_controller.go
New scenarios:
- set OFED wait to true when OFED is removed from CR and Pods are terminating
- clean OFED wait label from the node if it doesn't have NVIDIA nic anymore
> Fix behaviour for OFED wait label to handle additional scenarios

- config/manager/kustomization.yaml
- config/rbac/role.yaml
- controllers/hostdevicenetwork_controller.go
- controllers/ipoibnetwork_controller.go
- controllers/macvlannetwork_controller.go
- controllers/nicclusterpolicy_controller.go
- controllers/upgrade_controller.go
- manifests/state-multus-cni/0010-cluter_role.yml
This brings back the changes from https://github.com/Mellanox/network-operator/pull/596
Previously, the CI failed because apart from `mellanox/nicclusterpolicies` resource, `mellanox/nicclusterpolicies/status` also needs to be explicitely mentiones.
Other than that, multus cluster role also required wildcard permissions for k8s.cni.cncf.io group. Limited them to `network-attachment-definition`
> Remove wildcard permissions from controllers' roles

- README.md
- api/v1alpha1/nicclusterpolicy_types.go
- config/crd/bases/mellanox.com_nicclusterpolicies.yaml
- config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml
- deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml
- deployment/network-operator/values.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- hack/release.yaml
- manifests/state-rdma-device-plugin/0060_rdma-shared-dev-plugin-ds.yaml
Almost the same with **https://github.com/Mellanox/network-operator/pull/565**. Whichever is merged last needs to merge into the existing one
> Add support for CDI in k8s-rdma-shared-dev-plugin deployments

- manifests/state-nv-ipam-cni/040-nv-ipam-node.yaml
nv-ipam node has liveness and rediness probes and metrics endpoint. It is problematic to use hostNetwork: true because ports can be already used on the node by a different process. 
upstream nv-ipam node DS doesn't use hostNetwork https://github.com/Mellanox/nvidia-k8s-ipam/blob/11f148c7a7c6ed9a1daaeda927f01fda8331ec80/deploy/nv-ipam.yaml#L64
> Remove hostNetwork:true from nv-ipam-node spec

- Dockerfile
update base image to receive latest security fixes
> chore:  update base image to ubi8-micro 8.8

- config/manager/manager.yaml
- deployment/network-operator/templates/operator.yaml
Align the operator deployment yamls between
the Helm template and the kubebuilder generated
yaml in `config/manager/manager.yaml`.
> chore: Align deployment yaml

- deployment/network-operator/templates/role.yaml
Align Helm RBAC Role template to the kubebuilder generated file in `config/rbac/role.yaml`.
Some of the permissions were relocated to allow easier diff.
> chore: Align RBAC rules

- deployment/network-operator/charts/sriov-network-operator/templates/role.yaml
sriov network operator config daemon
requires access to events.
> fix: add missing roles in chart

- api/v1alpha1/nicclusterpolicy_webhook.go
- api/v1alpha1/nicclusterpolicy_webhook_test.go
In the admission controller, the `resourcePrefix` field in Device Plugins configuration is now validated to be a valid FQDN.
> fix: validate resourcePrefix in NCP DP

- deployment/network-operator/templates/operator.yaml
Remove `control-plane: {{ .Release.Name }}-controller` selector from the network-operator object in the helm chart
to fix helm upgrade behaviour.
With the current selector we will have the following error when trying to upgrade from the latest GA version (23.7)
```
helm upgrade -n nvidia-network-operator network-operator ./network-operator -f myvalues.yaml 
Error: UPGRADE FAILED: cannot patch "network-operator" with kind Deployment: Deployment.apps "network-operator" is i
nvalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"n
etwork-operator", "app.kubernetes.io/name":"network-operator", "control-plane":"network-operator-controller"}, Match
Expressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable       
```
The extra …
> fix: remove extra selector from network-operator Deployment

- example/sriov-network/sriov-network-node-policy-legacy.yaml
- example/sriov-network/sriov-network-node-policy-switchdev.yaml
It is recommended to use the following node selector in SRIOV network policy:
`feature.node.kubernetes.io/pci-15b3.present`
> chore: Update Node Selector for node policy

- config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml
- deployment/network-operator/values.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- hack/release.yaml
MOFED v23.10-0.5.5.0 is a GA version
> chore: Update MOFED to 23.10-0.5.5.0

- deployment/network-operator/templates/sriovnetwork.openshift.io_sriovoperatorconfig.yaml
We need to take into account SR-IOV Network Operator help values during SriovOperatorConfig deployment.
> fix: Allow to enable SR-IOV Network Operator Webhook

- deployment/network-operator/templates/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- deployment/network-operator/templates/scale-down-hook.yaml
- pkg/migrate/migrate.go
In order to allow migration from config map to IP Pool CRs in NV IPAM, the config map needs to be kept.
- Removing the state label will make sure it is not deleted as a stale object.
- Remove the helm hook annotation on NiClusterPolicy CR template, that causes delete and recreate of CR and the delete-cr hook. Note that this will prevent CR validation in install stage for admission controller.
- Make sure to stop existing Network Operator before updating CR, so that it does not delete the config map since config is removed.
> fix:  preserve NVIPAM CM after upgrade

- deployment/network-operator/templates/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- deployment/network-operator/templates/scale-down-hook.yaml
- pkg/migrate/migrate.go
In order to allow migration from config map to IP Pool CRs in NV IPAM, the config map needs to be kept.
Removing the state label will make sure it is not deleted as a stale object.
Remove the helm hook annotation on NiClusterPolicy CR template, that causes delete and recreate of CR and the delete-cr hook. Note that this will prevent CR validation in install stage for admission controller.
Make sure to stop existing Network Operator before updating CR, so that it does not delete the config map since config is removed.
> fix: preserve NVIPAM CM after upgrade

- deployment/network-operator/README.md
Add force flag  to Helm upgrade
> docs: Add force flag to Helm upgrade

- pkg/state/state_hostdevice_network.go
- pkg/state/state_ipoib_network.go
- pkg/state/state_macvlan_network.go
All CR instances are sharing the same state name, but they handled by a separate Reconcile loop. 
Stale objects removal logic doesn't support this scenario.
> fix: remove stale objects handling from *network CR states

- pkg/state/state_hostdevice_network.go
- pkg/state/state_ipoib_network.go
- pkg/state/state_macvlan_network.go
All CR instances are sharing the same state name, but they handled by a separate Reconcile loop. Stale objects removal logic doesn't support this scenario.
(cherry picked from commit 125e9a0f3e88e7ecd246966be6477889ba611e72)
> Remove stale objects handling from *network CR states

- deployment/network-operator/README.md
Remove scale down in upgrade documentation as it is implemented in Helm hook.
> docs: Remove scale down in upgrade

- pkg/consts/consts.go
- pkg/revision/revision.go
- pkg/revision/revision_suite_test.go
- pkg/revision/revision_test.go
- pkg/state/state_skel.go
Inject controller generated revision to all managed objects as annotation. 
The revision is later used to check if object update is required. 
This change should help to reduce amount of API calls to Kubernetes.
fixes #614
> feat: add controller revision to managed resources

- deployment/network-operator/templates/NOTES.txt
Add deprecation notice to helm notes in case
user deployed CR via helm.
This mode of operation is intended to be deprecated Users should transition to deploying CR independently post helm install/update
> docs: add deprecation notice

- Makefile
- api/v1alpha1/nicclusterpolicy_types.go
- api/v1alpha1/nicclusterpolicy_webhook.go
- api/v1alpha1/nicclusterpolicy_webhook_test.go
- config/crd/bases/mellanox.com_nicclusterpolicies.yaml
- config/manager/init_container_image_name_patch.yaml
- config/manager/kustomization.yaml
- deployment/network-operator/README.md
- deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml
- deployment/network-operator/templates/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- deployment/network-operator/templates/operator.yaml
- deployment/network-operator/values.yaml
- docs/automatic-ofed-upgrade.md
- hack/release.go
- hack/release.yaml
- hack/templates/config/manager/init_container_image_name_patch.template
- hack/templates/values/values.template
- manifests/state-ofed-driver/0010_service-account.openshift.yaml
- manifests/state-ofed-driver/0010_service-account.yaml
- manifests/state-ofed-driver/0020_cluster_role.yaml
- manifests/state-ofed-driver/0030_cluster_role_binding.yaml
- manifests/state-ofed-driver/0040_ofed_init_container_config-configmap.yaml
- manifests/state-ofed-driver/0050_ofed-driver-ds.yaml
- pkg/config/config.go
- pkg/state/state_ofed.go
- pkg/state/state_ofed_test.go
On Node startup, the OFED container takes some time to compile and load the driver. 
During that time, workloads might get scheduled on that Node.
When OFED is loaded, all existing PODs that use NVIDIA NICs will lose their network interfaces.
Some such PODs might silently fail or hang.
To avoid such a situation, before the OFED container is loaded, 
the Node should get Cordoned and Drained to ensure all workloads are rescheduled.
The Node should be un-cordoned when the driver is ready on it.
The safe driver loading feature is implemented as a part of the upgrade flow,
meaning safe driver loading is a special scenario of the upgrade procedure,
where we upgrade from the inbox driver to the containerized OFED.
depends on: #685
> feat: add support for safe driver loading feature

- controllers/upgrade_controller.go
This change is needed because common upgrade lib is using both labels and annotations to store upgrade state. 
This change increase performance of the upgrade controller.
> fix: add label changed predicate for node obj in upgrade controller

- manifests/state-ofed-driver/0050_ofed-driver-ds.yaml
- pkg/state/state_ofed.go
- pkg/state/state_ofed_test.go
- Add podAntiAffinity to MOFED
- Add unit test to check PodAntiAffinity rendering
- Add unit test to check NodeSelector rendering
- Extract methods in state_ofed for better readability
> feat: add podAntiAffinity to MOFED

- go.mod
- go.sum
Remove unneeded dependency from go.mod.
This was accidentally introduced as part of #715
> fix: remove apiserver from go.mod

- .github/workflows/build.yml
- Makefile
Add a check in the CI to ensure that go modules are up to date.
This will catch issues like #718 from recurring.
> fix: Add check for go modules

- deployment/network-operator/README.md
- deployment/network-operator/templates/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- deployment/network-operator/values.yaml
- hack/templates/values/values.template
- manifests/state-nv-ipam-cni/040-nv-ipam-node.yaml
- manifests/state-sriov-device-plugin/0030-sriov-dp-daemonset.yml
- pkg/state/continuity_check_test.go
- pkg/state/factory.go
- pkg/state/state_cni_plugins.go
- pkg/state/state_ib_kubernetes.go
- pkg/state/state_ipoib_cni.go
- pkg/state/state_multus_cni.go
- pkg/state/state_nic_feature_discovery.go
- pkg/state/state_nv_ipam_cni.go
- pkg/state/state_ofed.go
- pkg/state/state_shared_dp.go
- pkg/state/state_sriov_dp.go
- pkg/state/state_whereabouts_cni.go
Update README
Add continuity check unit test:
* This test renders all manifests to extract deployable containers' names and parses values.yaml from the helm chart to make sure that all containers are represented in the helm chart under the ResourceRequirements section
> feat: Configure container resources in the helm chart

- controllers/nicclusterpolicy_controller.go
- manifests/state-ofed-driver/0050_ofed-driver-ds.yaml
We already have a label which marks a pod as a driver pod which does not rely on the version of the driver. use it instead
> chore: remove driver-pod label

- .gitignore
- Makefile
- controllers/suite_test.go
- tools.go
Update the `setup-envtest` version and Kubernetes version for envtest used in the Makefile.
A couple of other small cleanups - removing broken `test-xml` make target and unused `tools.go` file.
> chore: Update envtest version and install process

- pkg/state/state_ofed.go
- pkg/state/state_ofed_test.go
Always set CREATE_IFNAME_UDEV to true env var as recent mofed driver container performs a more robust logic to preserve netev interface names via udev.
> chore: Update default env vars for mofed container

- deployment/network-operator/charts/sriov-network-operator/templates/certificate.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/operator.yaml
- deployment/network-operator/charts/sriov-network-operator/values.yaml
- deployment/network-operator/templates/sriovnetwork.openshift.io_sriovoperatorconfig.yaml
- deployment/network-operator/values.yaml
- hack/templates/values/values.template
Today it's cumbersome to enable admission controllers for SRIOV Network Operator because the user needs to create a secret manually. With this PR https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/561, it's possible to generate a self signed certificate so the user doesn't need to do manual steps to enable those admission controllers.
This PR just updates the chart to the latest chart found in the `master` branch of https://github.com/k8snetworkplumbingwg/sriov-network-operator which at the time was https://github.com/k8snetworkplumbingwg/sriov-network-operator/commit/233b99abed2645f626dea43b02179fcec0d661b4.
Another PR will enable proper support for admission controllers.
> chore: Update SR-IOV Network Operator chart to consume new cert logic

- Makefile
When deploying network-operator helm chart, the templates rely on chart.AppVersion when constructing the image url. To allow to automate chart publishing, consistent AppVersions need to be provided when chart is built.
Add a flag to helm package command in the make chart-build target
> fix: Update both chart and app version when bulding helm chart with Makefile

- config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml
- deployment/network-operator/values.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- hack/release.yaml
- manifests/state-ofed-driver/0050_ofed-driver-ds.yaml
latest MOFED build supports a better logic to create udev rule to preserve
netdev name on old(er) kernels.
bump mofed version and provide required mounts.
> feat: Support mofed udev logic

- deployment/network-operator/values.yaml
- hack/templates/values/values.template
Requires and is based on: https://github.com/Mellanox/network-operator/pull/709
This PR adds support for auto generated cert-manager certificates when user enables the SR-IOV Network Operator Admission Controllers via the Helm value `sriov-network-operator.operator.admissionControllers.enabled`.
This PR won't work until:
* a new image of SR-IOV Network Operator is published and the following value is updated https://github.com/vasrem/network-operator/blob/f125b8a67772fc31af6ced0b24c9249531e5e542/deployment/network-operator/values.yaml#L146
* a new image of SR-IOV Network Operator Webhook is published and the following value is updated https://github.com/vasrem/network-operator/blob/f125b8a67772fc31af6ced0b24c9249531e5e542/deployment/network-operator/values.yaml#L152
* This is needed to …
> feat: Support SR-IOV Network Operator Admission Controllers

- api/v1alpha1/nicclusterpolicy_types.go
- config/crd/bases/mellanox.com_nicclusterpolicies.yaml
- deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml
This is required to prevent the rendering
of this field in the OLM examples for Openshift.
> fix: remove default value for nv-ipam spec in NicClusterPolicy

- deployment/network-operator/values.yaml
- hack/release.go
- hack/release.yaml
- hack/templates/values/values.template
The goal of this PR is to adjust the SR-IOV NetOp webhook image on release to an image built via our release pipeline, similarly to what we do with most of the images related to SR-IOV when we make a new release.
Needed by https://github.com/Mellanox/network-operator/pull/710
> feat: Adjust SR-IOV NetOp webhook image on release

- Dockerfile
- config/default/kustomization.yaml
- config/default/manager_args_and_resource_limits.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/dev/drop_manager_args_and_resources.yaml
- config/dev/kustomization.yaml
- docs/skaffold.md
- skaffold.yaml
Adds a skaffold config that can be used to deploy and debug the network operator.
Related to https://github.com/Mellanox/network-operator/issues/576
> devtools: Add skaffold config for network-operator

- Dockerfile
Fix an issue introduced in #733 which breaks multi-arch docker builds.
This fix will re-enable building multi-arch images.
> fix: Re-enable multi-arch docker image builds

- .golangci.yml
- Makefile
- pkg/utils/utils.go
Bumps to some tooling in the Makefile. None of them bring major changes.
`helm v3.5.3` -> `helm v3.13.3`
`hadolint v1.23.0` -> `hadolint v2.12.0`
`golangci-lint v1.52.2` -> `golangci-lint v1.55.2`
> chore: Bump helm, hadolint, and golangci-lint

- docs/skaffold.md
Add information on how to configure VSCode to connect to the remote debugger instance opened by `skaffold`.
Part of #576
> docs: Add skaffold VSCode config

- Makefile
- bundle.Dockerfile
- bundle/manifests/mellanox.com_hostdevicenetworks.yaml
- bundle/manifests/mellanox.com_ipoibnetworks.yaml
- bundle/manifests/mellanox.com_macvlannetworks.yaml
- bundle/manifests/mellanox.com_nicclusterpolicies.yaml
- bundle/manifests/nvidia-network-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/crd/bases/mellanox.com_hostdevicenetworks.yaml
- config/crd/bases/mellanox.com_ipoibnetworks.yaml
- config/crd/bases/mellanox.com_macvlannetworks.yaml
- config/crd/bases/mellanox.com_nicclusterpolicies.yaml
- deployment/network-operator/crds/mellanox.com_hostdevicenetworks.yaml
- deployment/network-operator/crds/mellanox.com_ipoibnetworks.yaml
- deployment/network-operator/crds/mellanox.com_macvlannetworks.yaml
- deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml
This is a bump of controller tools and `operator-sdk` to their most recent versions. The resulting changes are minor. 
This PR also contains a base commit to regenerate the `operator-sdk` bundle to separate out changes resulting from the version bump from those resulting from the regeneration. 
This commit was done after running:  `DEFAULT_CHANNEL=v23.10.0 CHANNELS=v23.10.0 VERSION=23.10.0 TAG=network-operator:latest make bundle`. Changes in the `config` folder were excluded.
> chore: Bump operator-sdk and controller-tools

- Makefile
- docs/local-development.md
- hack/scripts/minikube-install.sh
- skaffold.yaml
Add a minikube development environment for the network operator. 
This development environment spins up a minikube cluster and runs the network operator using skaffold.
> devtools: Add minikube dev environment

- .github/dependabot.yaml
- .github/workflows/build.yml
- .github/workflows/commit-msg-chk.yaml
Bump conventional commit github action. This action was giving a security warning because of outdated dependencies.
Release: https://github.com/agenthunt/conventional-commit-checker-action/releases/tag/v2.0.0
> chore: Bump commit check github action

- manifests/state-container-networking-plugins/0010-container-networking-plugins-ds.yml
- manifests/state-ib-kubernetes/0070-deployment.yaml
- manifests/state-ipoib-cni/0050-ipoib-cni-ds.yml
- manifests/state-nic-feature-discovery/030-nic-feature-discovery-ds.yaml
- manifests/state-nv-ipam-cni/040-nv-ipam-controller.yaml
- manifests/state-nv-ipam-cni/040-nv-ipam-node.yaml
- manifests/state-ofed-driver/0050_ofed-driver-ds.yaml
- manifests/state-rdma-device-plugin/0060_rdma-shared-dev-plugin-ds.yaml
- manifests/state-sriov-device-plugin/0030-sriov-dp-daemonset.yml
- manifests/state-whereabouts-cni/0050-whereabouts-ds.yaml
Issue identified in https://github.com/Mellanox/network-operator/pull/769 and in particular https://github.com/Mellanox/network-operator/commit/bae3edd6cb0ecf83b7d2dd5c7530ec8e86e19248.
Before this change, always the branch under `{{- with index .RuntimeSpec.ContainerResources <REPLACE_WITH_CONTAINER_NAME> }}` would be executed and not the branch under `{{- else }}`.  This means that the default resources will never render.
This is because the `.RuntimeSpec.ContainerResources` would be empty and we try to check for a key in an empty map using index that [will always return something](https://cs.opensource.google/go/go/+/master:src/text/template/funcs.go;l=234). According to the [docs](https://pkg.go.dev/text/template@go1.21.6#hdr-Functions:~:text=%7B%7Bwith%20pipeline%7D%7D%20T1%20%7B%7Bel …
> fix: ensure default resources are rendered in all states

- manifests/state-multus-cni/0050-multus-ds.yml
- pkg/state/state_multus_cni_test.go
- pkg/state/state_test_common.go
This PR adds additional unit tests for the Multus CNI state. 
The `Sync()` function will be tested using envtest on the controller pkg. This will happen in a later PR.
In addition to that, this PR fixes a bug that was discovered while writing tests where default resources of Multus CNI wouldn't render correctly even when ContainerResources were not specified in the NicClusterPolicy. Additional PR will come to fix the behavior in other states that might have the same issue.
> fix: add unit tests for multus cni state

- Dockerfile
- Makefile
- skaffold.yaml
Make some changes to the dockerfile to speed up builds.
Main changes:
- Use the go cache to avoid full recompilation every time
- Remove the `-a` arg from `go build` to allow using precompiled packages from the cache
Time comparison versus master:
15s v 59s
<details>
```
Building Docker image...
[+] Building 58.8s (27/27) FINISHED                                                                                                                                                                       docker:default
=> [internal] load build definition from Dockerfile                                                                                                                                                                0.0s
=> => transferring dockerfile: 2.87kB …
```
> chore: Speed up image build

- Makefile
Fix-up a comment on the `go-install-tool` function inside the Makefile to reflect what it's actually doing.
This function was changed in https://github.com/Mellanox/network-operator/pull/755 but the comment was not updated.
> fix: Description of Makefile go-install-tool

- pkg/state/common_test.go
- pkg/state/state_cni_plugins.go
- pkg/state/state_cni_plugins_test.go
- pkg/state/state_multus_cni.go
- pkg/state/state_multus_cni_test.go
- pkg/state/state_whereabouts_cni.go
Add unit-test to CNI plugins state.
The test is a different package so that only public APIs are used.
> chore: add cni plugins test

- api/v1alpha1/validator/nicclusterpolicy_webhook.go
- controllers/hostdevicenetwork_controller.go
- controllers/ipoibnetwork_controller.go
- controllers/macvlannetwork_controller.go
- controllers/nicclusterpolicy_controller.go
- pkg/state/continuity_check_test.go
- pkg/state/factory.go
- pkg/state/state_cni_plugins.go
- pkg/state/state_cni_plugins_test.go
- pkg/state/state_hostdevice_network.go
- pkg/state/state_hostdevice_network_test.go
- pkg/state/state_ib_kubernetes.go
- pkg/state/state_ib_kubernetes_test.go
- pkg/state/state_ipoib_cni.go
- pkg/state/state_ipoib_cni_test.go
- pkg/state/state_ipoib_network.go
- pkg/state/state_ipoib_network_test.go
- pkg/state/state_macvlan_network.go
- pkg/state/state_multus_cni.go
- pkg/state/state_multus_cni_test.go
- pkg/state/state_nic_feature_discovery.go
- pkg/state/state_nv_ipam_cni.go
- pkg/state/state_ofed.go
- pkg/state/state_ofed_test.go
- pkg/state/state_shared_dp.go
- pkg/state/state_skel.go
- pkg/state/state_sriov_dp.go
- pkg/state/state_sriov_dp_test.go
- pkg/state/state_whereabouts_cni.go
k8s client already has a method to get scheme.
> refactor: remove redundant Scheme from state

- .gitignore
- Makefile
- config/dev/cainjection_in_hostdevicenetworks.yaml
- config/dev/cainjection_in_nicclusterpolicies.yaml
- config/dev/kustomization.yaml
- config/dev/manager_webhook_patch.yaml
- config/dev/webhook_in_hostdevicenetworks.yaml
- config/dev/webhook_in_nicclusterpolicies.yaml
- config/dev/webhookcainjection_patch.yaml
- hack/scripts/minikube-install.sh
This change enables the nicclusterpolicy and hostnetwork webhooks under the `dev-skaffold` make target.
This change means that users of the `dev/skaffold` kustomize target - used by default with the `skaffold.yaml` - will have to install cert manager.
> devtools: Enable webhooks in dev-skaffold

- Makefile
Remove the arch identifier for multi-arch images from being part of either the image name or the tag. Multiarch images will not have a unique name or tag per arch. Instead they must be referenced through the manifest and platform.
Signed-off-by: killianmuldoon <cilliancapi@gmail.com>
> fix: Remove architecture from image tag

- manifests/state-nic-feature-discovery/030-nic-feature-discovery-ds.yaml
- manifests/state-nv-ipam-cni/040-nv-ipam-node.yaml
If you try to add a toleration, it fails with the exception below. It is failing because the Toleration block is in a different level of indentation as `nvidia.com/gpu:NoSchedule`.
```
error converting YAML to JSON: yaml: line 28: did not find expected key
failed to unmarshal manifest /manifests/state-nv-ipam-cni/040-nv-ipam-node.yaml
github.com/Mellanox/network-operator/pkg/render.(*textTemplateRenderer).renderFile
/workspace/pkg/render/render.go:155
github.com/Mellanox/network-operator/pkg/render.(*textTemplateRenderer).RenderObjects
/workspace/pkg/render/render.go:81
github.com/Mellanox/network-operator/pkg/state.(*stateNVIPAMCNI).getManifestObjects
/workspace/pkg/state/state_nv_ipam_cni.go:157
github.com/Mellanox/network-operator/pkg/state.(*stateNVIPAMCNI).Sync …
```
> fix: Toleration indentation problem

- config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml
- deployment/network-operator/values.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- hack/release.yaml
(cherry picked from commit f45ba4bc906a2783ecb48cf5e081b3ccc115ec95)
> chore: Bump DOCA driver to v24.01-0.3.3.1.3

- config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml
- deployment/network-operator/values.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- hack/release.yaml
Bump DOCA driver to v24.01-0.3.3.1-0
> chore: Bump DOCA driver to v24.01-0.3.3.1-0

- manifests/state-hostdevice-network/0010-hostdevice-net-cr.yml
- pkg/state/common_test.go
- pkg/state/state_hostdevice_network_test.go
An empty IPAM string in the HostDeviceNetwork
Spec was rendered without brackets, making the
NAD config a not valid json.
> fix: hostdevicenetwork IPAM

- .github/workflows/build.yml
- Dockerfile
- go.mod
- go.sum
chore: Bump go to v1.21
v1.21 is in use in the gomod and toolchain of some of our dependencies - at least controller runtime. Starting from Go 1.21 the go mod will be automatically updated to ensure we're working with the right toolchain.
> chore: Bump go to v1.21

- docs/mofed-container-env-vars.md
- manifests/state-ofed-driver/0050_ofed-driver-ds.yaml
- pkg/state/state_ofed.go
- pkg/state/state_ofed_test.go
Introduce DriverInventoryPath to the OFED spec.
It represents a path to a persistent writable folder where OFED container can store its build artifacts. If the artifacts for the correct version and arch exist in this folder when the OFED container is started, they will be reused without driver being recompiled.
> feat: Allow to configure persistent driver inventory for the OFED driver to avoid recompilation between runs

- Makefile
- pkg/state/state_nic_feature_discovery.go
- pkg/state/state_nic_feature_discovery_test.go
- pkg/state/state_nv_ipam_cni_test.go
This PR adds tests for `GetManifestObjects` functions across the board. The purpose of these tests is to ensure that each and every field can be rendered, and to prevent regressions from changes in the yamls.
This PR includes #813 and should be held until that one merges.
> chore: Add missing tests for rendering manifests

- deployment/network-operator/README.md
Added documentation for the new variables exposed by DOCA Telemetry Service in the Network Operator helm chart.
Follow up to #768 
Signed-off-by: killianmuldoon <kmuldoon@nvidia.com>
> docs: Helm documentation for DTS

- api/v1alpha1/validator/nicclusterpolicy_webhook.go
- api/v1alpha1/validator/nicclusterpolicy_webhook_test.go
Backwards compatibility is maintained, in future versions we can readjust the regular expression (and respective tests) by removing the `?` quantifier at the end of the expression.
Example of old version string: 23.10-0.2.2.0
Example of old version string: 23.10-0.2.2.0.1 (with container version suffix)
Example of new version string: 24.01-0.3.3.1-0
Signed-off-by: Michael Zeevi <mzeevi@nvidia.com>
(cherry picked from commit e35704f1fea50b33926d2dc583ab51dff676bd26)
> feat: modify OFED version validation to support new scheme

- controllers/hostdevicenetwork_controller.go
- controllers/ipoibnetwork_controller.go
- controllers/macvlannetwork_controller.go
- controllers/nicclusterpolicy_controller.go
- controllers/suite_test.go
- controllers/upgrade_controller.go
- controllers/upgrade_controller_test.go
- main.go
- manifests/state-ofed-driver/0050_ofed-driver-ds.yaml
- pkg/migrate/migrate.go
- pkg/migrate/migrate_test.go
- pkg/migrate/suite_test.go
- pkg/nodeinfo/node_info.go
- pkg/nodeinfo/node_info_test.go
- pkg/state/dummy_provider.go
- pkg/state/state_ofed.go
- pkg/state/state_ofed_test.go
- pkg/state/state_skel.go
Mofed driver precompiled container images
are compiled using a specific Kernel.
As a result, the Mofed Driver DaemonSet should
have the Kernel as part of the Node Selector.
In addition, since there can be Nodes with different Kernel versions, a DaemonSet for each existing Kernel in the cluster is created.
> feat: Support multiple MOFED DS

- api/v1alpha1/validator/nicclusterpolicy_webhook.go
- api/v1alpha1/validator/nicclusterpolicy_webhook_test.go
- manifests/state-doca-telemetry-service/0010-doca-telemetry-service.yaml
Add webhook validation for DOCATelemetryService.
This checks that the image spec repository is valid and that the configMap passed into the configuration has a valid configmap name.
> feat: Add webhook validation for DOCATelemetryService

- README.md
- deployment/network-operator/README.md
- deployment/network-operator/values.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml
- hack/release.yaml
This version contains bug fixes and other improvements.
Change log for the version: https://github.com/Mellanox/nvidia-k8s-ipam/releases/tag/v0.1.2
Backport to v24.1.x
(cherry picked from commit de0d6b3d6db708fc9e8751276702305474c366e3)
> [v24.1.x] fix: update nv-ipam to v0.1.2

- config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml
- deployment/network-operator/values.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- hack/release.yaml
- manifests/state-ofed-driver/0050_ofed-driver-ds.yaml
Bump DOCA Driver to 24.04-0.4.0.0-0
Signed-off-by: killianmuldoon <kmuldoon@nvidia.com>
> chore: Bump DOCA Driver to `24.04-0.4.0.0-0`

- deployment/network-operator/README.md
The helm repository alias (_mellanox_) and URL (`https://mellanox.github.io/network-operator`) was outdated in the network-operator documentation.
This commit corrects it to use the up-to-date alias (_nvidia_) and URL (`https://helm.ngc.nvidia.com/nvidia`).
The issue may exist in other locations (repositories), but this is the "main" one.
> task: Update helm repo URL and alias

- deployment/network-operator/values.yaml
- hack/templates/values/values.template
Based on https://github.com/Mellanox/network-operator/issues/531
The deleted fields copy the default values of the sriov-network-operator chart. Dropping them doesn't affect the deployment.
> chore: Drop duplicated fields from the sriov-network-operator chart values

- config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml
- deployment/network-operator/values.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- hack/release.yaml
Bump doca driver to 24.04-0.6.2.0-0
> chore: Bump doca driver to 24.04-0.6.2.0-0

- deployment/network-operator/values.yaml
- hack/release.yaml
- hack/templates/values/values.template
update ovs-cni to the latest version and
enabled deployment by default
(cherry picked from commit 412f7aca105325542cea611820e3c5851130dea8)
> [v24.4.x] chore: Update ovs-cni to latest upstream version

- config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml
- deployment/network-operator/values.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- hack/release.yaml
Bump DOCA driver to v24.04-0.6.6.0-0
> chore: Bump DOCA driver to v24.04-0.6.6.0-0

- .github/workflows/build.yml
A separate PR to follow for the README badge
Might need to provide access to Mellanox org
> chore: Add coverage report to CI checks

- README.md
Coveralls is the supplier of the coverage data.
Need to have at least one merged PR with coverage to master to enable the badge
> chore: Add code coverage status badge to README

- deployment/network-operator/values.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- hack/release.yaml
Upgrade whereabouts version to 0.7.0
to fix the version incompatibility with SRIOV-network-operator
> chore: upgrade whereabouts to version 0.7.0

- .github/workflows/commit-msg-chk.yaml
As discussed with @e0ne , we wish to make commit message checking slightly less strict in PRs, i.e. to not enforce the commit message to have both a _message_ **and** _body_; instead of only enforce a _message_.
Reference commit as example:
```bash
git commit -m "this is the commit *message* (which will be enforced)
this is the commit *body* (which shall become optional).
it's separeted from the message by a blank line, often contains details
over several more lines, and finally closed by the same opening quote
as the message."
```
This is achieved by changing [the default behavior](https://github.com/agenthunt/conventional-commit-checker-action/blob/master/action.yml#L14) of the existing conventional-commit-checker action.
> feat(ci): set pr-body-regex action input to *not* require commit body

- pkg/state/state_ofed.go
Add support for RHEL filepaths in the ofed manifest generation. This enables the `repoConfig` and `certConfig` options when running OFED on RHEL nodes.
> feat: Add RHEL support in ofed config

- deployment/network-operator/values.yaml
- hack/release.yaml
- hack/templates/values/values.template
update ovs-cni to the latest version and
enabled deployment by default
> chore: Update ovs-cni to latest upstream version

- .github/workflows/network-operator-docker-and-helm-ci.yaml
- Makefile
this job will replace our legacy jenkins job, and be dependent on the new github action job for the network operator docker image.
> feat: add github actions job for helm publishing to CI workflow

- .github/workflows/network-operator-docker-and-helm-ci.yaml
Git tag events (regardless of the branch) would not trigger the old workflow, and push branch events would trigger it - including the Helm CI, which would sometimes not be able to determine any version to set, thus failing.
This commit fixes the above, by:
- Add a trigger for _pushed tag_ events.
- Determine docker tags and chart versions based on trigger event _type_.
- Add conditions to Helm CI job steps, allowing it to be skipped (but _not_ failed!) in cases where it is not required to run (such as an untagged intermediate commits on release branches).
> fix: refactor docker tag and helm version determination via triggers

- manifests/state-ofed-driver/0050_ofed-driver-ds.yaml
- pkg/nodeinfo/attributes.go
- pkg/nodeinfo/node_info.go
- pkg/state/state_ofed.go
- pkg/state/state_ofed_test.go
Add needed mounts for subscription in RHEL with non CRIO container runtime.
> feat: MOFED subscription mounts

- manifests/state-ib-kubernetes/0030-cluster_role.yaml
Network-operator doesn't allow to get * resources from k8s.cni.cncf.io. When ib-k8s deploys, it asks for more permissions thus failing to start
> fix: Align ib-kubernetes RBAC permissions with those of network-operator

- api/v1alpha1/nicclusterpolicy_types.go
- config/crd/bases/mellanox.com_hostdevicenetworks.yaml
- config/crd/bases/mellanox.com_nicclusterpolicies.yaml
- controllers/nicclusterpolicy_controller.go
- controllers/nicclusterpolicy_controller_test.go
- controllers/suite_test.go
- deployment/network-operator/crds/mellanox.com_hostdevicenetworks.yaml
- deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml
- pkg/state/state_ofed.go
Fixes #533
Example status:
```
status:
appliedStates:
- name: state-multus-cni
state: ignore
- name: state-container-networking-plugins
state: ignore
- name: state-ipoib-cni
state: ignore
- name: state-whereabouts-cni
state: ignore
- error: 'failed to create k8s objects from manifest: failed to render objects:
ForcePrecompiled is enabled and precompiled image was not found'
name: state-OFED
state: notReady
- name: state-SRIOV-device-plugin
state: ignore
```
> feat: Support errors on NCP status

- .github/workflows/network-operator-docker-and-helm-ci.yaml
Backporting the new CI workflow to a pre-created release branch.
> fix: cherrypick new docker & helm CI to release branch

- deployment/network-operator/charts/sriov-network-operator/README.md
- deployment/network-operator/charts/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovnetworknodepolicies.yaml
- deployment/network-operator/charts/sriov-network-operator/crds/sriovnetwork.openshift.io_sriovnetworknodestates.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/configmap.yaml
- deployment/network-operator/charts/sriov-network-operator/templates/role.yaml
- deployment/network-operator/charts/sriov-network-operator/values.yaml
Bump chart to https://github.com/k8snetworkplumbingwg/sriov-network-operator/tree/8d32f42b42b59a27864043ad22afa3741f197d9a/deployment/sriov-network-operator
This PR does not introduce 1o1 mapping with the upstream chart. There additional configuration related to RDMA CNI.
Here is the diff that is not committed when trying to create 1o1 mapping with the upstream chart.
<details>
<summary>Current Drift</summary>
```
diff --git b/deployment/network-operator/charts/sriov-network-operator/Chart.yaml a/deployment/network-operator/charts/sriov-network-operator/Chart.yaml
index 4fffae2..8c7a62e 100644
--- b/deployment/network-operator/charts/sriov-network-operator/Chart.yaml
+++ a/deployment/network-operator/charts/sriov-network-operator/Chart.yaml
@@ -1,6 +1,6 @@
apiVersion: v2
name: …
```
> chore: bump sriov netop chart

- manifests/state-ofed-driver/0050_ofed-driver-ds.yaml
We need to mount host `/etc/modprobe.d/ib_core.conf` config into the container to not break host RDMA subsystem configuration.
> fix: Mount `/etc/modprobe.d/ib_core.conf` to OFED container

- config/rbac/role.yaml
- controllers/nicclusterpolicy_controller.go
- deployment/network-operator/templates/role.yaml
- deployment/network-operator/values.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml
- hack/release.yaml
- manifests/state-nv-ipam-cni/005-nv-ipam.nvidia.com_cidrpools.yaml
- manifests/state-nv-ipam-cni/020-cluster-role.yaml
- manifests/state-nv-ipam-cni/035-webhook.yaml
This version contains support for static IPs and new CIDRPool API.
Changelog: https://github.com/Mellanox/nvidia-k8s-ipam/releases/tag/v0.2.0
> chore: update nv-ipam to v0.2.0

- config/rbac/role.yaml
- config/samples/mellanox.com_v1alpha1_nicclusterpolicy.yaml
- controllers/nicclusterpolicy_controller.go
- deployment/network-operator/templates/role.yaml
- deployment/network-operator/values.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- hack/release.yaml
- manifests/state-whereabouts-cni/0010-whereabouts.cni.cncf.io_ippools.yaml
- manifests/state-whereabouts-cni/0015-whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml
- manifests/state-whereabouts-cni/0020-cluster_role.yaml
- manifests/state-whereabouts-cni/0045-whereabouts-config.yaml
- manifests/state-whereabouts-cni/0050-whereabouts-ds.yaml
Bump versions of various components deployed by the network operator.
- update rdma-shared-device-plugin to 1.5.1
- update sriov-network-device-plugin to v3.7.0
- update containernetworking plugins to v1.5.0
- update ipoib-cni to v1.2.0
- update whereabouts to v0.7.0
- update ovs-cni-plugin to v0.34.0
- update rdma cni to v1.2.0
- update sriov cni to v2.8.0
- update ib sriov cni to v1.1.1
note: multus cni will be updated in a separate commit.
> chore: Bump versions

- pkg/state/state_hostdevice_network_test.go
- pkg/state/state_ipoib_network_test.go
- pkg/state/state_macvlan_network_test.go
To be able to restructure the state unit tests we have to move the constants of the unit test to the own scope.
> chore: move test consts to own scope of package state_test

- manifests/state-ofed-driver/0050_ofed-driver-ds.yaml
we have observed on some systems lsmod command timesout. current default is 1s. increase to 10s.
> fix: add timeout to mofed probes

- pkg/state/common_test.go
- pkg/state/state_hostdevice_network_test.go
- pkg/state/state_ipoib_network_test.go
- pkg/state/state_macvlan_network_test.go
- pkg/state/state_rdma_shared_device_plugin_test.go
> chore: implement new assert function for NAD unit tests

- .gitignore
- Makefile
- hack/release.go
- hack/release.yaml
- hack/templates/docs-versions-var/vars.template
Generate documentation var files to be used
in network-operator-docs repo.
> chore: generate docs versions var

- go.mod
- go.sum
https://nvd.nist.gov/vuln/detail/CVE-2024-41110
> chore: update docker dep due to CVE

- deployment/network-operator/values.yaml
- hack/templates/values/values.template
The `values.template` is updated to render a `values.yaml` containing the needed descriptions, and has to be updated for new fields if needed.
This is needed in order to properly render the `helm.rst` in Network-Operator-docs. **Note** All new fields will be in `General Parameters` section by default. If this is not desirable, the `helm.rst.gotmpl` has to be update in Network-Operator-docs.
See rendered doc: https://github.com/Mellanox/network-operator/blob/6ae08a018f019d12fc13d4630209e25cd22cc5ef/docs/charts/helm.rst
> feat: Add description to helm values

- manifests/state-doca-telemetry-service/0010-doca-telemetry-service.yaml
- manifests/state-doca-telemetry-service/0010_service-account.yaml
- manifests/state-doca-telemetry-service/0020_role.openshift.yaml
- manifests/state-doca-telemetry-service/0030_rolebinding.openshift.yaml
- pkg/state/common_test.go
- pkg/state/state_doca_telemetry_service.go
- pkg/state/state_doca_telemetry_service_test.go
Add support for OpenShift to the DOCA Telemetry Services deployment by adding a service account associated roles / rolebinding which gives access to the privileged securityContextConstraint.
> fix: Add openshift rolebinding to DOCA Telemetry Service

- deployment/network-operator/values.yaml
- hack/release.yaml
We need to update SR-IOV CNI to have it working with the latest Linux kernels and have [1] fix included.
[1] https://github.com/k8snetworkplumbingwg/sriov-cni/issues/303
> fix: Bump SR-IOV CNI to v2.8.1

- .github/workflows/docs-ci-trigger.yaml
This short workflow is used to trigger the new [downstream documentation CI workflow](https://github.com/Mellanox/network-operator-docs/pull/91).
> feat: add trigger for docs ci

- deployment/network-operator/values.yaml
- hack/templates/values/values.template
In order to render complex objects as yaml,
add a type hint for helm-docs
> bug: add format hint to helm docs

- api/v1alpha1/validator/nicclusterpolicy_webhook.go
- api/v1alpha1/validator/nicclusterpolicy_webhook_test.go
Before, if a user wouldn't specify config for any of the rdma shared DP or sriov DP, the process would panic. This is now fixed.
Also, split a function into 2 to pass the linter.
> bugfix: ensure that we don't panic on DP validations

- manifests/state-ofed-driver/0050_ofed-modules-blacklist-configmap.yaml
- manifests/state-ofed-driver/0060_ofed-driver-ds.yaml
- pkg/state/state_ofed_test.go
We should not allow to load inbox or OFED-on-host drivers if DOCA Driver container deployment is enabled.
(cherry picked from commit ea727667aaf7d3c7680fd335324dde759307367b)
> feat: Blacklist DOCA Drive modules on host

- cmd/apply-crds/main.go
We want to make this package public to make it re-usable for other projects.
> fix: Make apply-crds binary public useable

- api/v1alpha1/nicclusterpolicy_types.go
- config/crd/bases/mellanox.com_nicclusterpolicies.yaml
- deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml
Set the following fileds as required:
- pKeyGUIDPoolRangeStart
- pKeyGUIDPoolRangeEnd
- ufmSecret
> fix: Set required fields in ibKubernetes

- Dockerfile
- cmd/keep-ncp/main.go
- cmd/keep-ncp/main_test.go
- cmd/keep-ncp/suite_test.go
- deployment/network-operator/templates/keep-ncp-hook.yaml
Creation of NicClusterPolicy was removed from the Helm Chart.
In order to avoid deletion of the CR on Helm upgrade, a Helm hook adds a 'keep' annotation to the NCP if needed, before running the actual upgrade.
> bug: keep NCP on Helm upgrade

- manifests/state-doca-telemetry-service/0010-doca-telemetry-service.yaml
We need to run it after DOCA driver is started to be able successfully restart driver by a container.
> fix: Add 'nodeSelector' field for DTS deployment

- .github/workflows/docs-ci-trigger.yaml
Following `docs-ci-trigger` changes will initiate new `network-operator-docs` repo PR for new `tag`, `pull-request` cases, whenever there are helm values or api changes.
This PR is based on changes done in [#Mellanox/network-operator-docs/132](https://github.com/Mellanox/network-operator-docs/pull/132)
> chore: fixing dosc-ci to auto trigger docs repo PRS for helm, api changes

- manifests/state-multus-cni/0050-multus-ds.yml
- pkg/render/render.go
Multus pod has crashed due to changes in multus DS template, mainly command/args, between versions 24.7 and 24.10
The following solution is only a short term solution for fixing failed multus DS.
For next version we should introduce an inclusive solution for any other workloads dependencies provisioned by network-operator templates
> chore: fixing failed network-operator upgrade to 24.10 over crashing multus pod

- .github/workflows/ci.yaml
On tag event, a PR with new OCP bundle is created; its target branch should be:
- _master_ for **beta** tags,
- otherwise should be the **release branch**.
This change fixes that.
> bug: fix target branch for OCP bundle PR

- deployment/network-operator/values.yaml
- hack/release.yaml
nic-configuration-operator version should be the same as nic-configuration-operator-daemon.
> fix: update nic-configuration-operator version.

- Dockerfile
- deployment/network-operator/Chart.yaml
- deployment/network-operator/charts/maintenance-operator-chart/.helmignore
- deployment/network-operator/charts/maintenance-operator-chart/Chart.yaml
- deployment/network-operator/charts/maintenance-operator-chart/README.md
- deployment/network-operator/charts/maintenance-operator-chart/crds/maintenance.nvidia.com_maintenanceoperatorconfigs.yaml
- deployment/network-operator/charts/maintenance-operator-chart/crds/maintenance.nvidia.com_nodemaintenances.yaml
- deployment/network-operator/charts/maintenance-operator-chart/templates/_helpers.tpl
- deployment/network-operator/charts/maintenance-operator-chart/templates/certificates.yaml
- deployment/network-operator/charts/maintenance-operator-chart/templates/deployment.yaml
- deployment/network-operator/charts/maintenance-operator-chart/templates/metrics-service.yaml
- deployment/network-operator/charts/maintenance-operator-chart/templates/operatorconfig.yaml
- deployment/network-operator/charts/maintenance-operator-chart/templates/role.yaml
- deployment/network-operator/charts/maintenance-operator-chart/templates/role_binding.yaml
- deployment/network-operator/charts/maintenance-operator-chart/templates/serviceaccount.yaml
- deployment/network-operator/charts/maintenance-operator-chart/templates/webhook.yaml
- deployment/network-operator/charts/maintenance-operator-chart/values.yaml
- deployment/network-operator/templates/upgrade-crd-hook.yaml
- deployment/network-operator/values.yaml
- hack/release.go
- hack/release.yaml
- hack/templates/values/values.template
Adding maintenance operator charts
> task: Adding maintenance operator charts

- .github/workflows/ci.yaml
When creating the CI PR with updates to OCP bundle, the `bundle.Dockerfile` should be also commited.
> bug: add bundle.Dockerfile to CI PR

- README.md
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-full.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- example/dgx-helm-values.yaml
- hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-full.template
- hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.template
- hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.template
- hack/templates/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.template
Empty config in multus, empty multus config is created causing nodes to be in not ready state.
> bug: remove empty config in multus examples

- .github/workflows/ci.yaml
- push ocp-bundle on every merge
- tag format is short sha commit
> chore: Add push to OCP bundle in CI

- Makefile
- bundle/manifests/nvidia-network-operator.clusterserviceversion.yaml
- config/manager/init_container_image_name_patch.yaml
- hack/templates/config/manager/init_container_image_name_patch.template
For disconnected environment, OCP bundle should use only SHA  format for container images.
> chore: use sha for init container image

- .github/workflows/docs-ci-trigger.yaml
Auto docs-ci PR should be fixed in future. Meanwhile autp PR workflow changes have been reverted
> chore: Reverting since docs CI per PR is broken

- deployment/network-operator/values.yaml
- hack/templates/values/values.template
Previous version didn't support multi-arch
> bug: bump network-resources-injector version to support multi-arch

- .github/workflows/release-pr-checker.yaml
- .github/workflows/release.yaml
We need to start SR-IOV Network Operator release if Network Operator Release pipeline started.
> feat: Network Operator release trigger

- bundle/manifests/nvidia-network-operator.clusterserviceversion.yaml
- config/manager/init_container_image_name_patch.yaml
- deployment/network-operator/values.yaml
- hack/release.yaml
- hack/templates/values/values.template
This version contains updated dependencies and doesn't introduce any new functionality
> chore: Update network-operator-init-container to v0.0.3

- .github/workflows/release.yaml
Job failed with:
```
2025-01-20T06:34:22.5666372Z Switched to a new branch 'cidi/update-network-operator-to-v25.1.0-beta.3'
2025-01-20T06:34:23.3239441Z Error: stat hack/release.yaml: no such file or directory
```
> chore: release ci without sparse checkout

- api/v1alpha1/nicclusterpolicy_types.go
- config/crd/bases/mellanox.com_nicclusterpolicies.yaml
- controllers/nicclusterpolicy_controller_test.go
- deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml
- manifests/state-container-networking-plugins/0010-container-networking-plugins-ds.yml
- manifests/state-doca-telemetry-service/0010-doca-telemetry-service.yaml
- manifests/state-ib-kubernetes/0070-deployment.yaml
- manifests/state-ipoib-cni/0050-ipoib-cni-ds.yml
- manifests/state-multus-cni/0050-multus-ds.yml
- manifests/state-nic-feature-discovery/030-nic-feature-discovery-ds.yaml
- manifests/state-nv-ipam-cni/040-nv-ipam-controller.yaml
- manifests/state-nv-ipam-cni/040-nv-ipam-node.yaml
- manifests/state-rdma-shared-device-plugin/0060_rdma-shared-dev-plugin-ds.yaml
- manifests/state-sriov-device-plugin/0030-sriov-dp-daemonset.yaml
- manifests/state-whereabouts-cni/0050-whereabouts-ds.yaml
- pkg/render/render.go
- pkg/state/common_test.go
- pkg/state/state_cni_plugins_test.go
- pkg/state/state_doca_telemetry_service_test.go
- pkg/state/state_ib_kubernetes_test.go
- pkg/state/state_ipoib_cni_test.go
- pkg/state/state_multus_cni_test.go
- pkg/state/state_nic_feature_discovery_test.go
- pkg/state/state_nv_ipam_cni_test.go
- pkg/state/state_rdma_shared_device_plugin_test.go
- pkg/state/state_sriov_dp_test.go
In OCP disconnected environment, the mirrored images are not using tags but SHA256.
This change support boths format in the NCP except for DOCA-Driver.
> bug: support container image SHA256 version

- .github/workflows/docs-ci-trigger.yaml
this change is coupled with the change in network-operator: https://github.com/Mellanox/network-operator-docs/pull/166
The workflow also prints the URL to the downstream workflow, and its result is propagated (upstream will fail if downstream fails).
> fix: refactor docs-ci downstream trigger to operate via workflow_dispatch only

- .github/workflows/checks.yaml
Reading secrets is not allowed in PRs
Make target still available for local check
> chore: remove check doca validation

- .github/workflows/ci.yaml
Solution for bugs [like seen here](https://github.com/Mellanox/network-operator/actions/runs/12889112884/job/35935799562).
> fix: if chart version already exists then *won't* fail on chart-push

- .github/workflows/ci.yaml
```
export NETWORK_OPERATOR_VERSION=37831e1
go run -v  release.go --with-sha256 --templateDir ./templates/config/manager --outputDir ../config/manager/
ref nvcr.io/nvstaging/mellanox/network-operator:37831e1
ref ghcr.io/mellanox/network-operator-init-container:v0.0.3
ref nvcr.io/nvstaging/mellanox/sriov-network-operator:network-operator-25.1.0-rc.1
...
```
> bug: fix bundle on push

- .github/workflows/release-pr-checker.yaml
Need to specify flag with 'gh pr merge'
```
--merge, --rebase, or --squash required when not running interactively
```
See failure:
https://github.com/Mellanox/network-operator/actions/runs/13098322826/job/36544958292
> ci: PR checker interval

- .github/workflows/ci.yaml
```
export NETWORK_OPERATOR_VERSION=37831e1
go run -v  release.go --with-sha256 --templateDir ./templates/config/manager --outputDir ../config/manager/
ref nvcr.io/nvstaging/mellanox/network-operator:37831e1
ref ghcr.io/mellanox/network-operator-init-container:v0.0.3
ref nvcr.io/nvstaging/mellanox/sriov-network-operator:network-operator-25.1.0-rc.1
```
> bug: fix make ocp-bundle ci on push 

- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-full.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- hack/release.yaml
(cherry picked from commit 8a698dfa3214326042f6bf9e8adcf16f60a2e2c4)
> chore: Bump DOCA Driver to 25.01-0.5.4.0-0

- deployment/network-operator/templates/admission_controller.yaml
- deployment/network-operator/values.yaml
- hack/templates/values/values.template
In `ValidatingWebhookConfiguration` template `caBundle` was using server side tls cert instead of CA cert
> bug: fix admission_controller template while not using cert-manager

- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-full.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-nvidia-ipam.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp-hostdev.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ocp.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr.yaml
- hack/release.yaml
(cherry picked from commit 9616d0523bc02dbd8c3585bdb6c391030295d33a)
> chore: Bump DOCA Driver image to 25.01-0.5.6.0-0

- deployment/network-operator/templates/admission_controller.yaml
- deployment/network-operator/values.yaml
- hack/templates/values/values.template
In `ValidatingWebhookConfiguration` template caBundle was using server side tls cert instead of CA cert
> fix admission_controller template while not using cert-manager

- api/v1alpha1/nicclusterpolicy_types.go
- config/crd/bases/mellanox.com_nicclusterpolicies.yaml
- deployment/network-operator/crds/mellanox.com_nicclusterpolicies.yaml
- deployment/network-operator/values.yaml
- hack/templates/values/values.template
- The fix is only for the API docs that are reflected in official documentation
- API fields are not changed to not break API
> bug: replace MOFED to DOCA on API docs

- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-full.yaml
- example/crs/mellanox.com_v1alpha1_nicclusterpolicy_cr-ipoib.yaml
- hack/release.yaml
changelog: https://github.com/Mellanox/ipoib-cni/releases/tag/v1.2.1 CVE fixes and go version upgrade
> chore: upgrade ipoib-cni to v1.2.1 in v25.1.x

- .github/workflows/release.yaml
The PR updating the Network Operator Chart version and release.yaml for release flow should be based on the release branch if the version is not a beta.(RC+GA)
> ci: update version from release branch

- .github/workflows/release-pr-checker.yaml
Current branch protection rules require at least one approving review. If we want the cicd PRs to be merged automatically, we need to override these rules with `--admin` option
> fix: allow pr_checker job to override branch protection rules

- .github/workflows/docs-ci-trigger.yaml
Doc repo tries to get the SHA256 of the operator.
Wait until image is published before triggering doc repo.
> bug: docs CI wait for new image

- deployment/network-operator/charts/nic-configuration-operator-chart/crds/configuration.net.nvidia.com_nicconfigurationtemplates.yaml
- deployment/network-operator/charts/nic-configuration-operator-chart/crds/configuration.net.nvidia.com_nicdevices.yaml
- deployment/network-operator/charts/nic-configuration-operator-chart/crds/configuration.net.nvidia.com_nicfirmwaresources.yaml
- deployment/network-operator/charts/nic-configuration-operator-chart/crds/configuration.net.nvidia.com_nicfirmwaretemplates.yaml
- deployment/network-operator/charts/nic-configuration-operator-chart/templates/config-daemon.yaml
- deployment/network-operator/charts/nic-configuration-operator-chart/templates/nic-fw-storage-pvc.yaml
- deployment/network-operator/charts/nic-configuration-operator-chart/templates/operator.yaml
- deployment/network-operator/charts/nic-configuration-operator-chart/templates/role.yaml
missing CRDs lead to errors in the deployment
> fix: update NIC Configuration Operator helm chart

- manifests/state-spectrum-x-operator/0040-spectrumx-operator.yaml
- manifests/state-spectrum-x-operator/0050-flowcontroller-ds.yaml
Check if CM is specified before using it in template.
> fix: spectrumx-operator optional config map

- go.mod
- go.sum
> fix: bump k8s-operator-lib version to fix nodemaintenance deletion

- deployment/network-operator/charts/node-feature-discovery/templates/post-delete-job.yaml
- deployment/network-operator/charts/node-feature-discovery/values.yaml
- deployment/network-operator/values.yaml
- hack/templates/values/values.template
Rename previously created cleanupLabel variable to postDeleteCleanup in order to sync with community upstream
> chore:  Sync post delete label with upsteam

- .github/workflows/ci.yaml
Since the GA image is not yet published on GA tag, the OCP bundle CI should use the nvstaging registry.
> fix: OCP bundle CI GA use nvstaging

- .github/workflows/release.yaml
- hack/release.yaml
extend the existing release.yaml workflow to tag all managed repos that have the `sourceRepository` field in the release.yaml
Question to reviewers: do we want to extend the hack/release.yaml to contain some additional service info?
> chore: tag all managed repos on release

- controllers/nicclusterpolicy_controller.go
- controllers/nicclusterpolicy_controller_test.go
- controllers/predicate.go
- pkg/nodeinfo/filter.go
- pkg/nodeinfo/filter_test.go
- pkg/state/state_ofed.go
- pkg/state/state_ofed_test.go
Introduces taint-aware node filtering and OFED deployment.
- Controller now watches Node taint changes.
- New `NodeTaintChangedPredicate` and composite node filter (labels & taints) for OFED node selection.
- `state_ofed` uses this filter and adds a default `nvidia.com/gpu` toleration to OFED DaemonSets.
- NCP tolerations are respected.
- Extensive new tests for controller, filtering, and OFED state.
> fix: Implement Taint and Toleration Handling for NicClusterPolicy

- Makefile
bugfix:
the `?=` assignment operator is required for shell env var overrides of values, as used in other variables here.
> fix: missing conditional in assignment operator for BUNDLE_OCP_VERSIONS

- controllers/upgrade_controller.go
- go.mod
- go.sum
- main.go
Network-Operator adaptations for k8s-operator-lib changes, supporting [shared-requestor ](https://github.com/NVIDIA/k8s-operator-libs/blob/main/docs/automatic-ofed-upgrade.md#shared-requestor)flow
> feat: adding shared-requestor support in upgrade-controller

- .github/workflows/release-pr-checker.yaml
- .github/workflows/release.yaml
- hack/release.yaml
release.yaml now creates a single PR to release a new version. It creates release tags and branches in downstream components, then waits until all required images are available on the ngc staging. After that, it updates images versions in release.yaml, and pulls updated helm charts from sriov-network-operator and NFD.
Pros:
* A single run of CI is needed to test the release
* No PRs from downstream components
* Fork CI workflows now only need to build and push new images
Cons:
* None
> chore: simplify release CI

- .github/workflows/release.yaml
restoring it from staged doesn't roll back the changes
> fix: checkout ignored helm chart file on release update

- deployment/network-operator/charts/maintenance-operator-chart/README.md
- deployment/network-operator/charts/maintenance-operator-chart/crds/maintenance.nvidia.com_maintenanceoperatorconfigs.yaml
- deployment/network-operator/charts/maintenance-operator-chart/templates/deployment.yaml
- deployment/network-operator/charts/maintenance-operator-chart/templates/operatorconfig.yaml
- deployment/network-operator/charts/maintenance-operator-chart/values.yaml
- deployment/network-operator/values.yaml
- hack/templates/values/values.template
`maintenanceoperatorconfigs` can be deployed by other k8s operators, utilizing Maintennace OP. Using the following change we can control whether to deploy this object or not.
* Update maintenance OP Helm sub-chart.
* Add support in values.yaml to control 'maintenanceoperatorconfigs' deployment
> chore: Update Maintenance OP Helm sub-chart

- Makefile
- bundle/metadata/annotations.yaml
- hack/scripts/ocp-bundle-postprocess.sh
As discussed on RH Slack with @rollandf.
> feat: rhcos os-version change no longer requires an annotation for OCP catalog bundle

- controllers/suite_test.go
- controllers/upgrade_controller.go
- controllers/upgrade_controller_test.go
In case requestor-mode is set in driver's upgrade controller, there was a missing flow to cleanup existing `nodeMaintenance` objects, created by current requestor. 
New changes will cleanup `nodeMaintenance` objects once either `NicClusterPolicy` or `OFEDDriverSpec` are removed
> chore: adding nodeMaintenance cleanup in upgrade-controller

- .github/workflows/release.yaml
otherwise we can't check for helm chart updates
> fix: checkout maintenance op repo in the release pipeline

- .github/workflows/release.yaml
- hack/release.yaml
maintenance op chart has a different name pattern in the network operator, need to account for that
> fix: another small fix to helm charts in release CI

- pkg/state/state_ofed.go
- pkg/state/state_ofed_test.go
This PR adds a postStart lifecycle hook in the MOFED container to run update-ca-certificates (Ubuntu/Debian) or update-ca-trust (RHEL/SLES), ensuring system trust store picks up any mounted CA certs.
Tested on: Ubuntu 24.04
This avoids the need to rebuild the image just to inject CA certs.
> ofed-driver: Adjust mount path for Ubuntu system CA certificates

- pkg/state/state_ofed.go
- pkg/state/state_ofed_test.go
- Adjust mount path to /usr/local/share/ca-certificates
- Fix unit tests for cert mount validation
> fix: support custom CA certificate update on Ubuntu

- manifests/state-nic-configuration-operator/060-operator.yaml
- manifests/state-nic-configuration-operator/070-config-daemon.yaml
since the last update the functionality of the operator grew and the current resource requirements are not sufficient, which may lead to OOM errors on some setups. Let's increase the default values
> fix: increase default resource requirements for NIC Config Operator
